#!/usr/bin/env python3
"""The lookup table of design/04 *Damage formula*: 2^(x/40) for x in [-160, +80], in fixed point.

One entry per integer x, index x + 160, value round(2^16 * 2^(x/40)) (D-140: 16 fractional bits,
each entry rounded to nearest). Written once to the contracts and to the client, so that both read
the same data and neither can drift from the other:

  contracts/logic/src/helpers/exp2_table.cairo    the table, as a constant array of u32
  client/sim/src/exp2.ts                          the table and the clamped lookup

  python3 contracts/tools/exp2_table.py           writes both files
  python3 contracts/tools/exp2_table.py --check   writes nothing; exits 1 when either file differs
                                                  from what would be written (CI)

Both files are written the way their formatter leaves them (`scarb fmt` packs the Cairo array to the
line width; prettier puts one bigint per line), so that `scarb fmt --check`, `prettier --check` and
`--check` here agree.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CAIRO_PATH = os.path.join(ROOT, "contracts", "logic", "src", "helpers", "exp2_table.cairo")
TS_PATH = os.path.join(ROOT, "client", "sim", "src", "exp2.ts")
LOW, HIGH, SCALE_BITS = -160, 80, 16
WIDTH = 100  # scarb fmt line width


def table():
    """round(2^16 * 2^(x/40)) for x in [LOW, HIGH], exact: the result is decided in integers."""
    out = []
    for x in range(LOW, HIGH + 1):
        # v is the integer with (v - 1/2)^40 <= 2^(640 + x) < (v + 1/2)^40, that is
        # (2v - 1)^40 <= 2^(680 + x) < (2v + 1)^40. The float is only the starting guess.
        target = 2 ** (680 + x)
        v = int(round(2 ** (SCALE_BITS + x / 40)))
        while (2 * v - 1) ** 40 > target:
            v -= 1
        while (2 * v + 1) ** 40 <= target:
            v += 1
        out.append(v)
    return out


def pack(values, indent):
    """Values packed to WIDTH columns, as `scarb fmt` packs an array literal."""
    lines, line = [], " " * indent
    for v in values:
        item = f"{v},"
        if line.strip() and len(line) + 1 + len(item) > WIDTH:
            lines.append(line)
            line = " " * indent
        line += (" " if line.strip() else "") + item
    lines.append(line)
    return lines


def cairo(t):
    out = [
        "//! Generated by contracts/tools/exp2_table.py: do not edit by hand (`--check` fails in CI).",
        "//! 2^(x/40) for x in [-160, +80], index x + 160, in fixed point with 16 fractional bits, each",
        "//! entry rounded to nearest (design/04 *Damage formula*, D-140).",
        "",
        "// A constant table: no type owns it, so it is a constant and not a function (CAIRO §7).",
        f"pub const EXP2_X40: [u32; {len(t)}] = [",
    ]
    out += pack(t, 4)
    out += ["];", ""]
    return "\n".join(out)


def typescript(t):
    out = [
        "// Generated by contracts/tools/exp2_table.py: do not edit by hand (`--check` fails in CI).",
        "// 2^(x/40) for x in [-160, +80], index x + 160, in fixed point with 16 fractional bits, each",
        "// entry rounded to nearest (design/04 *Damage formula*, D-140).",
        "",
        f"export const EXP2_LOW = {LOW};",
        f"export const EXP2_HIGH = {HIGH};",
        "",
        "export const EXP2_X40: readonly bigint[] = [",
    ]
    out += [f"  {v}n," for v in t]  # prettier puts one bigint per line
    out += [
        "];",
        "",
        "/**",
        " * 2^(x/40) in fixed point with 16 fractional bits; `x` outside [-160, +80] clamps (D-140).",
        " * `x` is an integer, like the contracts' `i32`: a fraction or NaN throws a RangeError, so that",
        " * the simulation never carries an undefined damage factor.",
        " */",
        "export function exp2(x: number): bigint {",
        "  if (!Number.isInteger(x)) throw new RangeError(`exp2: x must be an integer, got ${x}`);",
        "  const clamped = Math.min(Math.max(x, EXP2_LOW), EXP2_HIGH);",
        "  return EXP2_X40[clamped - EXP2_LOW]!;",
        "}",
        "",
    ]
    return "\n".join(out)


def main():
    t = table()
    # Bytes, not text: read and written in binary, so that no newline translation hides a CRLF or a CR.
    files = {CAIRO_PATH: cairo(t).encode("utf-8"), TS_PATH: typescript(t).encode("utf-8")}
    if "--check" in sys.argv[1:]:
        stale = []
        for path, data in files.items():
            try:
                with open(path, "rb") as f:
                    same = f.read() == data
            except FileNotFoundError:
                same = False
            if not same:
                stale.append(os.path.relpath(path, ROOT))
        if stale:
            print("stale or edited, run python3 contracts/tools/exp2_table.py: " + ", ".join(stale))
            sys.exit(1)
        print(f"{len(t)} entries, both files current")
        return
    for path, data in files.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.write(data)
    print(f"{len(t)} entries, from {t[0]} (x = {LOW}) to {t[-1]} (x = {HIGH})")


if __name__ == "__main__":
    main()
