#!/usr/bin/env python3
"""The lookup table of design/04 *Damage formula*: 2^(x/40) for x in [-160, +80], in fixed point.

One entry per integer x, index x + 160, value round(2^(x/40) * 2^16). Written once to the Cairo
library and to the TypeScript mirror, so that both read the same data (content is data): the
table is not a place where the two can diverge, the arithmetic around it is.

  python3 spikes/SPK-4/gen_table.py
  scripts/lock.sh scarb --manifest-path spikes/SPK-4/cairo/Scarb.toml fmt --workspace   # packs the arrays
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
LOW, HIGH, SCALE_BITS = -160, 80, 16


def table():
    # Exact rounding from integers: v = round(2^16 * 2^(x/40)) is the integer v with
    # (v - 1/2)^40 <= 2^(640 + x) < (v + 1/2)^40, i.e. (2v - 1)^40 <= 2^(680 + x) < (2v + 1)^40.
    out = []
    for x in range(LOW, HIGH + 1):
        target = 2 ** (680 + x)
        v = int(round(2 ** (SCALE_BITS + x / 40)))
        while (2 * v - 1) ** 40 > target:
            v -= 1
        while (2 * v + 1) ** 40 <= target:
            v += 1
        out.append(v)
    return out


def main():
    t = table()
    n = len(t)
    cairo = [
        "//! Generated by spikes/SPK-4/gen_table.py: do not edit by hand.",
        "//! 2^(x/40) for x in [-160, +80], index x + 160, in fixed point with 16 fractional bits",
        "//! (design/04 *Damage formula*).",
        "",
        f"pub const POW2_X40_LEN: u32 = {n};",
        "pub const POW2_X40_SHIFT: u32 = 65536;",
        "",
        f"pub const POW2_X40: [u32; {n}] = [",
    ]
    cairo += [f"    {v}," for v in t]
    cairo += ["];", ""]
    # Bit i of a 128-bit limb, and bit i of a window layer as a felt (i < 240): the bitmaps.
    cairo += ["/// 2^i, i in [0, 128): bit i of a limb.", "pub const POW2_U128: [u128; 128] = ["]
    cairo += [f"    {2 ** i}," for i in range(128)]
    cairo += ["];", "", "/// 2^i, i in [0, 240): tile i of a window layer.", "pub const POW2_FELT: [felt252; 240] = ["]
    cairo += [f"    {hex(2 ** i)}," for i in range(240)]
    cairo += ["];", ""]
    with open(os.path.join(HERE, "cairo", "logic", "src", "table.cairo"), "w", encoding="utf-8") as f:
        f.write("\n".join(cairo))
    ts = [
        "// Generated by spikes/SPK-4/gen_table.py: do not edit by hand.",
        "// 2^(x/40) for x in [-160, +80], index x + 160, in fixed point with 16 fractional bits",
        "// (design/04 *Damage formula*).",
        "",
        "export const POW2_X40: readonly bigint[] = [",
    ]
    ts += [f"  {v}n," for v in t]
    ts += ["];", ""]
    with open(os.path.join(HERE, "ts", "table.ts"), "w", encoding="utf-8") as f:
        f.write("\n".join(ts))
    print(f"{n} entries, from {t[0]} (x = {LOW}) to {t[-1]} (x = {HIGH})")


if __name__ == "__main__":
    main()
