#!/usr/bin/env python3
"""SPK-14: write src/tables.cairo, the constants of the hexagonal chunk, its window and its
generation, computed on the plain model (geometry.py, generation.py).

    python3 spikes/SPK-14/gen_tables.py && scarb --manifest-path spikes/SPK-14/Scarb.toml fmt
"""
import os

from geometry import AREA, ROWS, STARTS, hi, index, lo, tile

HERE = os.path.dirname(os.path.abspath(__file__))
P = 2**251 + 17 * 2**192 + 1
LIMB = 2**128


def felt(v):
    return hex(v % P)


def array(name, kind, values, doc):
    body = ", ".join(felt(v) if kind == "felt252" else hex(v) for v in values)
    return f"/// {doc}\npub const {name}: [{kind}; {len(values)}] = [{body}];\n"


def const(name, kind, value, doc):
    return f"/// {doc}\npub const {name}: {kind} = {felt(value) if kind == 'felt252' else hex(value)};\n"


def window_tables():
    out = []
    out.append(array("FIRST", "u8", STARTS, "The first bit of each row of a hexagonal chunk."))
    out.append(array("QLO", "u8", [lo(r) for r in range(ROWS)], "The lowest axial `q` of each row."))
    out.append(array("QHI", "u8", [hi(r) for r in range(ROWS)], "The highest axial `q` of each row."))
    out.append(array("TILE", "u16", [q + 32 * r for q, r in (tile(i) for i in range(AREA))],
                     "The tile of each bit: `q + 32 r`."))
    below = [(1 << k) - 1 for k in range(AREA + 1)]
    out.append(array("BELOW_LOW", "u128", [b % LIMB for b in below],
                     "The low limb of `2^k - 1`, the bits below `k`, for `k` in `0..=251`."))
    out.append(array("BELOW_HIGH", "u128", [b // LIMB for b in below],
                     "The high limb of `2^k - 1`."))
    interior = sum(1 << (15 * y + x) for y in range(1, 15) for x in range(1, 14))
    out.append(const("WINDOW_INTERIOR_LOW", "u128", interior % LIMB,
                     "The interior of the 15 x 16 window, low limb (its ring is wall)."))
    out.append(const("WINDOW_INTERIOR_HIGH", "u128", interior // LIMB,
                     "The interior of the 15 x 16 window, high limb."))
    return out


def main():
    out = ["//! Generated by gen_tables.py: do not edit by hand.\n"]
    out += window_tables()
    try:
        from generation import tables as generation_tables
    except ImportError:
        generation_tables = None
    if generation_tables is not None:
        out += generation_tables(array, const)
    path = os.path.join(HERE, "src", "tables.cairo")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {path}")


if __name__ == "__main__":
    assert index(*tile(250)) == 250
    main()
