#!/usr/bin/env python3
"""SPK-7: write src/tables.cairo, the constants of the assembly, the generation, the flood and the
line-of-sight tables, computed on the Python model (model.py).

    python3 spikes/SPK-7/gen_tables.py
"""
import os

from model import W, WINDOW_H, axial, between, hex_distance, offset

HERE = os.path.dirname(os.path.abspath(__file__))
P = 2**251 + 17 * 2**192 + 1


def inv2(k):
    return pow(2, -k, P)


def rect(cols, rows):
    return sum(1 << (y * W + x) for y in rows for x in cols)


def felt(v):
    return hex(v % P)


def array(name, kind, values, doc):
    body = ", ".join(felt(v) if kind == "felt252" else str(v) for v in values)
    return f"/// {doc}\npub const {name}: [{kind}; {len(values)}] = [{body}];\n"


def const(name, kind, value, doc):
    return f"/// {doc}\npub const {name}: {kind} = {felt(value) if kind == 'felt252' else hex(value)};\n"


def even_rows(height, flip):
    """Bits of the rows whose GLOBAL parity is even (odd-r: their North and South neighbours are at
    x - 1 and x)."""
    return sum(rect(range(W), [y]) for y in range(height) if (y % 2 == 0) != flip)


def los_table(anchor):
    """Masks of the tiles strictly between `anchor` and every tile within 6 of it, by axial offset
    (dq, dr), index (dr + 6) * 13 + (dq + 6); 0 beyond 6 (never read)."""
    aq, ar = axial(*anchor)
    out = []
    for dr in range(-6, 7):
        for dq in range(-6, 7):
            if max(abs(dq), abs(dr), abs(dq + dr)) > 6:
                out.append(0)
                continue
            target = offset(aq + dq, ar + dr)
            assert 1 <= target[0] <= 13 and 1 <= target[1] <= 14, target
            tiles = between(anchor, target)
            assert set(tiles) == set(between(target, anchor)), (anchor, target)
            assert hex_distance(anchor, target) == max(abs(dq), abs(dr), abs(dq + dr))
            out.append(sum(1 << (y * W + x) for x, y in tiles))
    return out


def check_los_shift():
    """The tables anchored at (7, 8) and (7, 7) hold, shifted by `source - anchor`, the exact tiles
    between every pair of interior tiles within 6 of each other (no tile leaves the window)."""
    tables = {0: (los_table((7, 8)), 8 * W + 7), 1: (los_table((7, 7)), 7 * W + 7)}
    pairs = 0
    for y1 in range(1, 15):
        for x1 in range(1, 14):
            table, anchor = tables[y1 % 2]
            q1, r1 = axial(x1, y1)
            for y2 in range(1, 15):
                for x2 in range(1, 14):
                    q2, r2 = axial(x2, y2)
                    dq, dr = q2 - q1, r2 - r1
                    if max(abs(dq), abs(dr), abs(dq + dr)) > 6:
                        continue
                    shift = (y1 * W + x1) - anchor
                    mask = table[(dr + 6) * 13 + dq + 6]
                    moved = mask << shift if shift >= 0 else mask >> -shift
                    # A right shift drops no bit: it is an exact field product
                    assert shift >= 0 or mask & ((1 << -shift) - 1) == 0
                    expected = sum(1 << (y * W + x) for x, y in between((x1, y1), (x2, y2)))
                    assert moved == expected, ((x1, y1), (x2, y2))
                    pairs += 1
    return pairs


def main():
    out = ["//! Generated by gen_tables.py from model.py: do not edit by hand.\n"]
    # --- assembly (ADR-0006 §4, N-3): a rectangle of a chunk is (columns) x (rows) ------------------
    out.append(array("COLS_FROM", "felt252", [(1 << W) - (1 << dx) for dx in range(W)],
                     "Columns `dx..14` of one row: `2^15 - 2^dx`."))
    out.append(array("COLS_TO", "felt252", [(1 << dx) - 1 for dx in range(W)],
                     "Columns `0..dx - 1` of one row: `2^dx - 1`."))
    out.append(array("ROWS_FROM", "felt252", [sum(1 << (W * r) for r in range(dy, 15)) for dy in range(W)],
                     "Rows `dy..14` of a chunk, one bit per row at column 0."))
    out.append(array("ROWS_TO", "felt252", [sum(1 << (W * r) for r in range(0, dy + 1)) for dy in range(W)],
                     "Rows `0..dy` of a chunk, one bit per row at column 0."))
    out.append(const("WINDOW_INTERIOR", "felt252", rect(range(1, 14), range(1, 15)),
                     "Interior of the 15 x 16 window: its ring is wall."))
    # --- flood (N-8), the window's layout: origin on an even global row ---------------------------
    even = even_rows(WINDOW_H, False)
    out.append(const("WINDOW_EVEN_LOW", "u128", even & (2**128 - 1), "Even rows of the window, low limb."))
    out.append(const("WINDOW_EVEN_HIGH", "u128", even >> 128, "Even rows of the window, high limb."))
    up, down = 1 << (W - 1), inv2(W + 1)
    out.append(const("UP", "felt252", up, "2^(W - 1): up shift of the even rows."))
    out.append(const("DOWN", "felt252", down, "2^-(W + 1): down shift of the even rows."))
    inv_2 = inv2(1)
    out.append(const("AROUND_EVEN", "felt252", (inv_2 + 2 + 3 * (up + down)) % P,
                     "Field sum of the 6 neighbour offsets of an even-row tile."))
    out.append(const("AROUND_ODD", "felt252", (inv_2 + 2 + 3 * (2 * up + 2 * down)) % P,
                     "Field sum of the 6 neighbour offsets of an odd-row tile."))
    # --- generation (N-1, N-2) ---------------------------------------------------------------------
    out.append(const("CHUNK_INTERIOR", "felt252", rect(range(1, 14), range(1, 14)),
                     "Interior of a chunk, 13 x 13: what the automaton evolves."))
    out.append(const("SPINE", "felt252", rect(range(1, 14), [7]) | rect([7], range(1, 14)),
                     "Row 7 and column 7 of the interior: every line from an opening meets it."))
    out.append(const("COL_EAST", "felt252", rect([0], range(1, 14)), "Ring column x = 0, corners excluded."))
    out.append(const("COL_WEST", "felt252", rect([14], range(1, 14)), "Ring column x = 14, corners excluded."))
    out.append(const("ROW_SOUTH", "felt252", rect(range(1, 14), [0]), "Ring row y = 0, corners excluded."))
    out.append(const("ROW_NORTH", "felt252", rect(range(1, 14), [14]), "Ring row y = 14, corners excluded."))
    out.append(array("CHUNK_EVEN", "felt252", [even_rows(15, False), even_rows(15, True)],
                     "Rows of a chunk on even GLOBAL rows: `[0]` a chunk starting on an even row, `[1]` on an odd one (the parity flag)."))
    out.append(const("LOW30", "u128", 2**30 - 1, "Rows 0 and 1 of a chunk."))
    out.append(const("LINE_EAST", "felt252", sum(1 << k for k in range(1, 7)),
                     "From an opening at x = 0 to x = 1..6 of its row, one product."))
    out.append(const("LINE_WEST", "felt252", sum(inv2(k) for k in range(1, 7)) % P,
                     "From an opening at x = 14 to x = 8..13 of its row, one exact product."))
    out.append(const("LINE_SOUTH", "felt252", sum(1 << (W * k) for k in range(1, 7)),
                     "From an opening at y = 0 to y = 1..6 of its column."))
    out.append(const("LINE_NORTH", "felt252", sum(inv2(W * k) for k in range(1, 7)) % P,
                     "From an opening at y = 14 to y = 8..13 of its column, one exact product."))
    # --- line of sight (N-5) ------------------------------------------------------------------------
    pairs = check_los_shift()
    out.append(array("LOS_EVEN", "felt252", los_table((7, 8)),
                     "Tiles strictly between (7, 8) and the tile at axial offset (dq, dr), |d| <= 6, index (dr + 6) * 13 + dq + 6."))
    out.append(array("LOS_ODD", "felt252", los_table((7, 7)),
                     "The same from (7, 7), for sources on odd rows."))
    path = os.path.join(HERE, "src", "tables.cairo")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {path}; line-of-sight tables checked on {pairs} ordered pairs of interior tiles")


if __name__ == "__main__":
    main()
