#!/usr/bin/env python3
"""SPK-7: shared vectors of the flood (fix loop 1). The same inputs run in the Python model
(`model.shared_flood`, here) and in Cairo (`flood::shared_flood`, `test_flood::test_flood_shared_vectors`),
and must give the same number of layers, the same goblin distances and the same reached tiles.

    python3 spikes/SPK-7/vectors.py          # checks, then writes src/vectors.cairo (then scarb fmt)

The rule both sides follow: the flood stops when no target is left to reach (checked before each
layer: no target, no layer beyond the start), when the frontier runs out, or at the limit (D-127).
A target on tile 0 (a corner of the ring, never next to an interior tile) is never reached: it
forces the flood to run to its limit or to the end of the frontier, as a pure-layer benchmark needs.
"""
import os
import re

from model import W, bits_to_set, shared_flood

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = open(os.path.join(HERE, "src", "boards.cairo")).read()


def const(name):
    return int(re.search(rf"pub const {name}: felt252 = (0x[0-9a-f]+);", SOURCE).group(1), 16)


def tiles(name):
    body = re.search(rf"pub const {name}: \[u8; 8\] = \[([^\]]*)\];", SOURCE).group(1)
    return [int(v) for v in body.replace("\n", " ").split(",") if v.strip()]


BOARDS = {
    "CAPPED_TERRAIN": const("CAPPED_TERRAIN"),
    "DEEP_TERRAIN": const("DEEP_TERRAIN"),
    "DEEP_EVEN_TERRAIN": const("DEEP_EVEN_TERRAIN"),
}
GOBLINS = {"none": [], "unreachable": [0], "CAPPED_GOBLINS": tiles("CAPPED_GOBLINS"),
           "DEEP_GOBLINS": tiles("DEEP_GOBLINS")}
UNLIMITED = 255

# (board, start, targets, limit, expected layers including the start)
CASES = [
    ("CAPPED_TERRAIN", 112, "none", 15, 1),
    ("CAPPED_TERRAIN", 112, "none", UNLIMITED, 1),
    ("DEEP_EVEN_TERRAIN", 127, "none", 15, 1),
    ("DEEP_EVEN_TERRAIN", 127, "none", UNLIMITED, 1),
    ("CAPPED_TERRAIN", 112, "unreachable", 15, 16),
    ("CAPPED_TERRAIN", 112, "unreachable", UNLIMITED, 22),
    ("DEEP_EVEN_TERRAIN", 127, "unreachable", 15, 16),
    ("DEEP_EVEN_TERRAIN", 127, "unreachable", UNLIMITED, 93),
    ("CAPPED_TERRAIN", 112, "CAPPED_GOBLINS", 15, 16),
    ("CAPPED_TERRAIN", 112, "CAPPED_GOBLINS", UNLIMITED, 16),
    ("DEEP_TERRAIN", 112, "DEEP_GOBLINS", 15, 16),
    ("DEEP_TERRAIN", 112, "DEEP_GOBLINS", UNLIMITED, 83),
]


def tile(i):
    return (i % W, i // W)


def run(board, start, targets, limit):
    terrain = bits_to_set(BOARDS[board], W, 16)
    goblins = [tile(t) for t in GOBLINS[targets]]
    occupied = {g for g in goblins if g in terrain}
    layers, dist, _, _ = shared_flood(terrain, occupied, tile(start), goblins,
                                      None if limit == UNLIMITED else limit)
    reached = sum(1 << (y * W + x) for layer in layers for x, y in layer)
    return len(layers), dist, reached


def main():
    rows = []
    for board, start, targets, limit, expected in CASES:
        layers, dist, reached = run(board, start, targets, limit)
        assert layers == expected, (board, start, targets, limit, layers, expected)
        print(f"{board:<18} start {start:>3} targets {targets:<15} limit {limit:>3}: {layers:>3} layers, distances {dist}")
        rows.append((board, start, targets, limit, layers, dist, reached))
    out = ["//! Generated by vectors.py from model.py: do not edit by hand. Shared vectors of the flood:",
           "//! `(terrain, start, targets, limit, layers, distances, reached)`, distances one byte per",
           "//! target (as `flood::distance_of`), reached the union of the layers.\n",
           "use crate::boards::{CAPPED_GOBLINS, CAPPED_TERRAIN, DEEP_EVEN_TERRAIN, DEEP_GOBLINS, DEEP_TERRAIN};\n",
           "pub fn vectors() -> Array<(felt252, u8, Span<u8>, u8, u32, felt252, felt252)> {",
           "    array!["]
    for board, start, targets, limit, layers, dist, reached in rows:
        span = {"none": "array![].span()", "unreachable": "array![0].span()"}.get(targets, f"{targets}.span()")
        packed = sum(d << (8 * j) for j, d in enumerate(dist))
        out.append(f"        ({board}, {start}, {span}, {limit}, {layers}, {hex(packed)}, {hex(reached)}),")
    out += ["    ]", "}"]
    path = os.path.join(HERE, "src", "vectors.cairo")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {path}: {len(rows)} vectors, every layer count as expected")


if __name__ == "__main__":
    main()
