#!/usr/bin/env python3
"""Gas budgets of the game's Cairo workspace, enforced by a tool (docs/CAIRO.md §2).

Runs `snforge test --workspace` in the workspace (default `contracts/`) through the build lock,
reads the l2 gas snforge measured for every test, reads the `#[available_gas(l2_gas: N)]` of every
test from the sources, and:

  (default)   writes docs/BUDGETS.md and one GAS.md per package, deterministically;
  --check     writes nothing; fails when a test has no budget, when a budget is loose
              (N > ceil(1.05 x measured)) or when a generated file differs from the one on disk;
  --report    prints the gas table of a REPORT.md (COMMON §7): before = docs/BUDGETS.md of
              origin/main, after = this run, budget.

A budget below ceil(1.05 x measured) is fine (lowering needs nothing) as long as the test passes.
Date and commit of a row are provenance: a row keeps the ones already in docs/BUDGETS.md while its
measure and budget do not change, else it takes the committer date and short hash of HEAD, so the
same run on the same commit gives the same bytes. A row changed in a working tree names the commit
the change was measured on, which is the parent of the commit that carries it.

A package opts in by being a member of the workspace given by --workspace (default `contracts/`);
each workspace has its own budgets file (--budgets, default docs/BUDGETS.md). The spikes are their
own workspaces or packages and stay out unless run with --workspace <dir> --budgets <file>.

  python3 scripts/gas_budgets.py [--check | --report] [--workspace DIR] [--budgets FILE]
                                 [--no-lock] [--from-output FILE]

--no-lock runs snforge directly (the CI has no build lock). --from-output reads a saved snforge
output instead of running the tests (debugging).
"""

import argparse
import glob
import os
import re
import subprocess
import sys
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULT = re.compile(
    r"^\[(PASS|FAIL)\]\s+(\S+)\s+\(l1_gas: ~(\d+), l1_data_gas: ~(\d+), l2_gas: ~(\d+)\)"
)
COLLECTED = re.compile(r"^Collected \d+ test\(s\) from (\S+) package")
BUDGET = re.compile(r"#\[available_gas\(\s*l2_gas:\s*(\d+)\s*\)\]")
ATTR = re.compile(r"#\[[^\]]*\]")
FN = re.compile(r"^\s*(?:pub\s+)?fn\s+(\w+)")
MARKER = "<!-- generated by scripts/gas_budgets.py: do not edit by hand -->"


def budget_for(measured):
    """N = ceil(1.05 x measured), in integers."""
    return (measured * 105 + 99) // 100


def run(cmd, cwd):
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def workspace_packages(ws):
    """{package name: directory} of the members of the workspace at ws (a repository path)."""
    with open(os.path.join(ws, "Scarb.toml"), "rb") as f:
        members = tomllib.load(f)["workspace"]["members"]
    packages = {}
    for pattern in members:
        for path in sorted(glob.glob(os.path.join(ws, pattern))):
            manifest = os.path.join(path, "Scarb.toml")
            if os.path.isfile(manifest):
                with open(manifest, "rb") as f:
                    packages[tomllib.load(f)["package"]["name"]] = path
    return packages


def parse_output(text):
    """[(package, test path, l1, l1 data, l2)] of the passed tests; raises on a failed one."""
    rows, package, failed = [], None, []
    for line in text.splitlines():
        m = COLLECTED.match(line)
        if m:
            package = m.group(1)
            continue
        m = RESULT.match(line)
        if not m:
            continue
        status, name, l1, l1d, l2 = m.groups()
        if status == "FAIL":
            failed.append(name)
        elif package is None:
            raise SystemExit(f"test {name} came before any 'Collected ... package' line")
        else:
            name = re.sub(r"^\w+?_(?:integrationtest|unittest)::", "", name, count=1)
            rows.append((package, name, int(l1), int(l1d), int(l2)))
    if failed:
        raise SystemExit("failed tests (a budget exceeded is a failed test):\n  " + "\n  ".join(failed))
    return rows


def declared_tests(path):
    """{function: (budget or None, ignored)} of the `#[test]` functions of one source file."""
    tests, pending = {}, []
    with open(path) as f:
        for raw in f:
            line = raw.split("//")[0]
            attrs = ATTR.findall(line)
            if attrs:
                pending += attrs
                continue
            m = FN.match(line)
            if m:
                if "#[test]" in pending:
                    b = next((BUDGET.fullmatch(a) for a in pending if BUDGET.fullmatch(a)), None)
                    tests[m.group(1)] = (int(b.group(1)) if b else None, "#[ignore]" in pending)
                pending = []
            elif line.strip():
                pending = []
    return tests


def package_tests(pkg_dir):
    """{function: [(file stem, budget, ignored)]} over the package's src/ and tests/."""
    found = {}
    for sub in ("src", "tests"):
        for path in sorted(glob.glob(os.path.join(pkg_dir, sub, "**", "*.cairo"), recursive=True)):
            stem = os.path.splitext(os.path.basename(path))[0]
            for fn, (budget, ignored) in declared_tests(path).items():
                found.setdefault(fn, []).append((stem, budget, ignored))
    return found


def collect(ws, output):
    """(rows, problems): rows are dicts of package, test, measured, budget, l1, l1d."""
    packages = workspace_packages(ws)
    declared = {name: package_tests(path) for name, path in packages.items()}
    measured, problems, rows = {}, [], []
    for package, test, l1, l1d, l2 in parse_output(output):
        if package not in packages:
            continue
        measured[(package, test)] = True
        segments = test.split("::")
        cands = declared[package].get(segments[-1], [])
        by_stem = [c for c in cands if c[0] in segments[:-1]]
        pick = by_stem if by_stem else cands
        if len(pick) != 1:
            problems.append(f"{package}::{test}: cannot tell which source function this is")
            budget = None
        else:
            budget = pick[0][1]
        rows.append(
            {"package": package, "test": test, "measured": l2, "budget": budget, "l1": l1, "l1d": l1d}
        )
        if budget is None:
            problems.append(f"{package}::{test}: no #[available_gas(l2_gas: N)]")
        elif budget > budget_for(l2):
            problems.append(
                f"{package}::{test}: budget {budget} is loose, measured {l2} allows "
                f"{budget_for(l2)} (ceil(1.05 x measured))"
            )
    seen = {(r["package"], r["test"].split("::")[-1]) for r in rows}
    for package, fns in declared.items():
        for fn, cands in fns.items():
            if any(not ign for _, _, ign in cands) and (package, fn) not in seen:
                problems.append(f"{package}::{fn}: declared #[test] but not measured by the run")
    rows.sort(key=lambda r: (r["package"], r["test"]))
    return rows, problems, packages


def parse_budgets(text):
    """{(package, test): (measured, budget, date, commit)} from a BUDGETS.md."""
    rows = {}
    for line in text.splitlines():
        cells = [c.strip().strip("`") for c in line.strip().strip("|").split("|")]
        if len(cells) == 6 and cells[2].isdigit() and cells[3].isdigit():
            rows[(cells[0], cells[1])] = (int(cells[2]), int(cells[3]), cells[4], cells[5])
    return rows


def head():
    date = run(["git", "show", "-s", "--format=%cs", "HEAD"], ROOT).stdout.strip()
    commit = run(["git", "rev-parse", "--short=7", "HEAD"], ROOT).stdout.strip()
    return date, commit


def read(path):
    try:
        with open(path) as f:
            return f.read()
    except FileNotFoundError:
        return ""


def render(rows, previous, ws, packages):
    """{path: text} of docs/BUDGETS.md-style file and the GAS.md of each package."""
    date, commit = head()
    for r in rows:
        old = previous.get((r["package"], r["test"]))
        if old and old[0] == r["measured"] and old[1] == r["budget"]:
            r["date"], r["commit"] = old[2], old[3]
        else:
            r["date"], r["commit"] = date, commit
    budgets = [
        "# Gas budgets",
        "",
        MARKER,
        "",
        f"Source of truth for the cost budgets of `{ws}/` (docs/CAIRO.md §2, OPERATIONS §5). "
        "Written from a test run by `python3 scripts/gas_budgets.py`, checked in the CI by "
        "`--check`; never edit a figure by hand. Measured and budget are l2 gas as snforge "
        "reports them; budget = ceil(1.05 × measured). Date and commit are those of HEAD when "
        "the row's figures last changed.",
        "",
        "| Package | Test | Measured (l2 gas) | Budget (l2 gas) | Date | Commit |",
        "|---|---|---:|---:|---|---|",
    ]
    for r in rows:
        budgets.append(
            f"| {r['package']} | `{r['test']}` | {r['measured']} | {r['budget']} "
            f"| {r['date']} | {r['commit']} |"
        )
    out = {"BUDGETS": "\n".join(budgets) + "\n"}
    for package, path in packages.items():
        mine = [r for r in rows if r["package"] == package]
        gas = [
            f"# Gas of {package}",
            "",
            MARKER,
            "",
            "Detail of every test of the package, from the same run as docs/BUDGETS.md. "
            "Headroom is the budget over the measure.",
            "",
            "| Test | l2 gas | Budget | Headroom | l1 gas | l1 data gas | Date | Commit |",
            "|---|---:|---:|---:|---:|---:|---|---|",
        ]
        for r in mine:
            head_room = f"{(r['budget'] - r['measured']) * 100 / r['measured']:.2f} %"
            gas.append(
                f"| `{r['test']}` | {r['measured']} | {r['budget']} | {head_room} | {r['l1']} "
                f"| {r['l1d']} | {r['date']} | {r['commit']} |"
            )
        out[os.path.join(path, "GAS.md")] = "\n".join(gas) + "\n"
    return out


def report(rows, base):
    """The gas table of a REPORT.md, COMMON §7."""
    before = parse_budgets(base)
    lines = [
        "| Entrypoint or algorithm | Before | After | Budget | Note |",
        "|---|---:|---:|---:|---|",
    ]
    for r in rows:
        old = before.pop((r["package"], r["test"]), None)
        if old is None:
            b, note = "—", "new"
        elif old[0] == r["measured"]:
            b, note = str(old[0]), "unchanged"
        else:
            b, note = str(old[0]), f"{(r['measured'] - old[0]) * 100 / old[0]:+.1f} %"
        lines.append(
            f"| {r['package']}::{r['test']} | {b} | {r['measured']} | {r['budget']} | {note} |"
        )
    for (package, test), old in sorted(before.items()):
        lines.append(f"| {package}::{test} | {old[0]} | — | — | removed |")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--report", action="store_true")
    ap.add_argument("--workspace", default="contracts")
    ap.add_argument("--budgets", default="docs/BUDGETS.md")
    ap.add_argument("--no-lock", action="store_true")
    ap.add_argument("--from-output")
    args = ap.parse_args()
    os.chdir(ROOT)

    if args.from_output:
        text = read(args.from_output)
    else:
        cmd = ["snforge", "test", "--workspace"]
        if not args.no_lock:
            cmd = [os.path.join(ROOT, "scripts", "lock.sh"), "--heavy"] + cmd
        res = run(cmd, os.path.join(ROOT, args.workspace))
        text = res.stdout
        if res.returncode != 0:
            sys.stderr.write(text + res.stderr)
            raise SystemExit(f"snforge test failed (exit {res.returncode})")
    rows, problems, packages = collect(args.workspace, text)
    if not rows:
        raise SystemExit("the run measured no test")

    if args.report:
        base = run(["git", "show", f"origin/main:{args.budgets}"], ROOT)
        sys.stdout.write(report(rows, base.stdout if base.returncode == 0 else ""))
        return

    files = render(rows, parse_budgets(read(args.budgets)), args.workspace, packages)
    files[args.budgets] = files.pop("BUDGETS")
    if args.check:
        for path, text in files.items():
            if read(path) != text:
                problems.append(f"{path} is stale against the run: rerun scripts/gas_budgets.py")
        for p in problems:
            print(f"gas check: {p}", file=sys.stderr)
        if problems:
            raise SystemExit(1)
        print(f"gas check: {len(rows)} tests, every budget is ceil(1.05 x measured) or lower, "
              f"{len(files)} files current")
        return

    for p in problems:
        print(f"gas: {p}", file=sys.stderr)
    for path, text in files.items():
        with open(path, "w") as f:
            f.write(text)
        print(f"wrote {path}")
    if problems:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
