#!/usr/bin/env python3
"""Gas budgets of the game's Cairo workspace, enforced by a tool (docs/CAIRO.md §2).

Runs `snforge test --workspace --fuzzer-seed 1` in the workspace (default `contracts/`) through the
build lock, reads the l2 gas snforge measured for every test, reads the `#[available_gas(l2_gas: N)]`
of every declared test from the sources, and:

  (default)    writes docs/BUDGETS.md and one GAS.md per package, deterministically;
  --check      writes nothing; fails on any problem below or when a generated file differs from disk;
  --report     prints the gas table of a REPORT.md (COMMON §7): before = docs/BUDGETS.md of
               origin/main, after = this run, budget, note; fails on any problem;
  --self-test  runs the fixtures of this script (snforge output lines, Cairo sources); no Scarb.

Problems, per test identified by its full path `package::module::test` (never by function name):
  * a declared test (`#[test]` or `#[test_case]`, `#[ignore]`d ones included) without a budget;
  * a budget above ceil(1.05 x measured) (a budget below is fine: lowering needs nothing, and a test
    over its budget already fails in snforge);
  * a declared test the run did not measure (an `#[ignore]`d one is not measured: only the presence
    of its budget is checked, its row says "ignored"); a measured test with no source declaration;
  * a budget higher than the one in origin/main's docs/BUDGETS.md, unless the line just above the
    `#[available_gas]` attribute is the comment `// gas: raised, <reason>` (CAIRO §2: a raise needs a
    written reason and the orchestrator's agreement; --report shows "raised: <reason>" in the Note
    column for the orchestrator to see);
  * a date/commit kept from the existing BUDGETS.md whose commit is not an ancestor of origin/main
    (git merge-base --is-ancestor) or whose committer date differs from the date column.
Fuzz and parameterized tests have ONE budget for all their runs or cases: N = ceil(1.05 x the most
expensive) (CAIRO §2). A fuzz test's measured figure is the MAXIMUM l2 gas over its runs (run with a
fixed seed, so the figure is reproducible). Parameterized tests (`#[test_case]`): each generated case
(test_sum_1_2_3) is its own row, mapped to its source function; the function's budget is checked
against the most expensive case.
Modules gated by a cfg other than `cfg(test)` are not evaluated, but every test in them must still
carry its budget attribute: it is checked, and the test is listed as "cfg-gated, not measured"
unless the run measured it.

Date and commit of a row are provenance: a row keeps the ones already in docs/BUDGETS.md while its
measure and budget do not change, else it takes the committer date and short hash of the merge base
of HEAD and origin/main (a commit that stays in main's history after a squash merge; HEAD when
origin/main is not known). The same run on the same commit gives the same bytes.

A package opts in by being a member of the workspace given by --workspace (default `contracts/`);
each workspace has its own budgets file (--budgets, default docs/BUDGETS.md). The spikes stay out
unless run with --workspace <dir> --budgets <file>.

  python3 scripts/gas_budgets.py [--check | --report | --self-test] [--workspace DIR]
                                 [--budgets FILE] [--no-lock] [--from-output FILE]

--no-lock runs snforge directly (the CI has no build lock). --from-output reads a saved snforge
output instead of running the tests (debugging).
"""

import argparse
import glob
import os
import re
import subprocess
import sys
import tomllib
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLAIN = re.compile(
    r"^\[(PASS)\]\s+(\S+)\s+\(l1_gas: ~(\d+), l1_data_gas: ~(\d+), l2_gas: ~(\d+)\)"
)
FUZZ = re.compile(
    r"^\[PASS\]\s+(\S+)\s+\(runs: \d+, \(l1_gas: \{max: ~(\d+)[^)]*?l1_data_gas: \{max: ~(\d+)"
    r"[^)]*?l2_gas: \{max: ~(\d+)"
)
FAIL = re.compile(r"^\[FAIL\]\s+(\S+)")
COLLECTED = re.compile(r"^Collected \d+ test\(s\) from (\S+) package")
BUDGET = re.compile(r"#\[\s*available_gas\(\s*l2_gas:\s*(\d+)\s*\)\s*\]")
RAISED = re.compile(r"^//\s*gas:\s*raised,\s*(\S.*)$")
TOKEN = re.compile(r"#\[[^\]]*\]|\bmod\s+(\w+)\s*\{|\bfn\s+(\w+)|[{};]")
BLANK = re.compile(r"//[^\n]*|'(?:[^'\\\n]|\\.)*'|\"(?:[^\"\\\n]|\\.)*\"")
MARKER = "<!-- generated by scripts/gas_budgets.py: do not edit by hand -->"


def budget_for(measured):
    """N = ceil(1.05 x measured), in integers."""
    return (measured * 105 + 99) // 100


def run(cmd, cwd=ROOT, env=None):
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, env=env)


# ---------------------------------------------------------------- sources

class Decl:
    """A declared test function: full path, budget, and what the attributes say."""

    def __init__(self, key, file, budget, line, reason, ignored, cases, gated):
        self.key, self.file, self.budget, self.line = key, file, budget, line
        self.reason, self.ignored, self.cases, self.gated = reason, ignored, cases, gated


def parse_source(text, prefix, file="<source>"):
    """Declared tests of one source file; `prefix` is the module path of the file itself."""
    comments = {}
    for n, line in enumerate(text.splitlines(), 1):
        if line.lstrip().startswith("//"):
            comments[n] = line.strip()
    clean = BLANK.sub(lambda m: re.sub(r"[^\n]", " ", m.group(0)), text)
    decls, stack, pending = [], [], []  # stack: (module name or None, gated)
    for m in TOKEN.finditer(clean):
        tok = m.group(0)
        if tok.startswith("#["):
            pending.append((tok, m.start()))
        elif m.group(1):
            gated = any(_gates(a) for a, _ in pending)
            stack.append((m.group(1), gated))
            pending = []
        elif m.group(2):
            attrs = [a for a, _ in pending]
            is_test = any(re.fullmatch(r"#\[\s*test\s*\]", a) or a.startswith("#[test_case") for a in attrs)
            if is_test:
                budget, line, reason = None, None, None
                for a, pos in pending:
                    b = BUDGET.fullmatch(a)
                    if b:
                        budget = int(b.group(1))
                        line = clean.count("\n", 0, pos) + 1
                        r = RAISED.match(comments.get(line - 1, ""))
                        reason = r.group(1).strip() if r else None
                mods = [n for n, _ in stack if n]
                decls.append(
                    Decl(
                        "::".join(prefix + mods + [m.group(2)]),
                        file,
                        budget,
                        line,
                        reason,
                        any(re.fullmatch(r"#\[\s*ignore\s*\]", a) for a in attrs),
                        sum(a.startswith("#[test_case") for a in attrs),
                        any(g for _, g in stack) or any(_gates(a) for a in attrs),
                    )
                )
            pending = []
        elif tok == "{":
            stack.append((None, False))
            pending = []
        elif tok == "}":
            if stack:
                stack.pop()
            pending = []
        else:  # ;
            pending = []
    return decls


def _gates(attr):
    """True for a cfg attribute other than the plain `cfg(test)` (not evaluated here)."""
    return attr.startswith("#[cfg(") and re.sub(r"\s+", "", attr) != "#[cfg(test)]"


def package_decls(pkg_dir):
    """Declared tests of a package: src/ (unit tests) and tests/ (integration tests)."""
    decls = []
    for sub in ("src", "tests"):
        base = os.path.join(pkg_dir, sub)
        for path in sorted(glob.glob(os.path.join(base, "**", "*.cairo"), recursive=True)):
            segs = os.path.splitext(os.path.relpath(path, base))[0].split(os.sep)
            if segs == ["lib"]:
                segs = []
            with open(path) as f:
                decls += parse_source(f.read(), segs, os.path.relpath(path, ROOT))
    return decls


# ---------------------------------------------------------------- snforge output

def parse_output(text):
    """[(package, test path, l1, l1 data, l2)] of the passed tests (l2 is the max over the runs
    of a fuzz test); raises on a failed one. Paths lose the target prefix (`<pkg>_integrationtest::`
    or `<pkg>::`), so they read `module::test`."""
    rows, package, failed = [], None, []
    for line in text.splitlines():
        m = COLLECTED.match(line)
        if m:
            package = m.group(1)
            continue
        m = FAIL.match(line)
        if m:
            failed.append(m.group(1))
            continue
        m = PLAIN.match(line)
        if m:
            _, name, l1, l1d, l2 = m.groups()
        else:
            m = FUZZ.match(line)
            if not m:
                continue
            name, l1, l1d, l2 = m.groups()
        if package is None:
            raise SystemExit(f"test {name} came before any 'Collected ... package' line")
        for prefix in (f"{package}_integrationtest::", f"{package}::"):
            if name.startswith(prefix):
                name = name[len(prefix):]
                break
        rows.append((package, name, int(l1), int(l1d), int(l2)))
    if failed:
        raise SystemExit("failed tests (a budget exceeded is a failed test):\n  " + "\n  ".join(failed))
    return rows


# ---------------------------------------------------------------- analysis

def analyse(package, decls, measured, baseline=None):
    """(rows, problems, notes) of one package. `measured` is [(test path, l1, l1d, l2)];
    `baseline` is {(package, test): budget} of origin/main, or None when unknown."""
    problems, notes, rows = [], [], []
    by_key = {}
    for d in decls:
        by_key.setdefault(d.key, []).append(d)
    for key, ds in by_key.items():
        if len(ds) > 1:
            problems.append(f"{package}::{key}: declared {len(ds)} times ({', '.join(d.file for d in ds)})")
    mapped = {d.key: [] for d in decls}
    for name, l1, l1d, l2 in measured:
        d = by_key.get(name, [None])[0]
        if d is None:  # a generated #[test_case] name: <function>_<arguments>
            cands = [c for c in decls if c.cases and name.startswith(c.key + "_")]
            d = max(cands, key=lambda c: len(c.key), default=None)
        if d is None:
            problems.append(f"{package}::{name}: measured, but no #[test] declaration found in the sources")
            continue
        mapped[d.key].append((name, l1, l1d, l2))
    for d in decls:
        full = f"{package}::{d.key}"
        where = f"{d.file}"
        got = mapped[d.key]
        if d.budget is None:
            problems.append(f"{full}: no #[available_gas(l2_gas: N)] ({where})")
        if not got:
            if d.ignored:
                rows.append(_row(package, d.key, None, d, 0, 0))
            elif d.gated:
                notes.append(f"{full}: cfg-gated, not measured (only its budget attribute is checked)")
            else:
                problems.append(f"{full}: declared #[test] but not measured by the run ({where})")
            continue
        if d.cases and len(got) != d.cases:
            problems.append(f"{full}: {d.cases} #[test_case] declared, {len(got)} measured")
        for name, l1, l1d, l2 in got:
            rows.append(_row(package, name, l2, d, l1, l1d))
        if d.budget is not None:
            top = max(g[3] for g in got)
            if d.budget > budget_for(top):
                problems.append(
                    f"{full}: budget {d.budget} is loose, measured {top} allows {budget_for(top)} "
                    f"(ceil(1.05 x measured))"
                )
    for r in rows:
        old = (baseline or {}).get((package, r["test"]))
        if r["budget"] is not None and old is not None and r["budget"] > old:
            r["raised"] = r["reason"] or ""
            if not r["reason"]:
                problems.append(
                    f"{package}::{r['test']}: budget raised {old} -> {r['budget']} without a "
                    f"`// gas: raised, <reason>` line just above the #[available_gas] attribute"
                )
    return rows, problems, notes


def _row(package, test, l2, d, l1, l1d):
    return {"package": package, "test": test, "measured": l2, "budget": d.budget, "l1": l1,
            "l1d": l1d, "reason": d.reason}


# ---------------------------------------------------------------- workspace, git, files

def workspace_packages(ws):
    """{package name: directory} of the members of the workspace at ws (a repository path)."""
    with open(os.path.join(ws, "Scarb.toml"), "rb") as f:
        members = tomllib.load(f)["workspace"]["members"]
    packages = {}
    for pattern in members:
        for path in sorted(glob.glob(os.path.join(ws, pattern))):
            manifest = os.path.join(path, "Scarb.toml")
            if os.path.isfile(manifest):
                with open(manifest, "rb") as f:
                    packages[tomllib.load(f)["package"]["name"]] = path
    return packages


def parse_budgets(text):
    """{(package, test): (measured or None if ignored, budget, date, commit)} of a BUDGETS.md."""
    rows = {}
    for line in text.splitlines():
        cells = [c.strip().strip("`") for c in line.strip().strip("|").split("|")]
        if len(cells) == 6 and (cells[2].isdigit() or cells[2] == "ignored") and cells[3].isdigit():
            measured = int(cells[2]) if cells[2].isdigit() else None
            rows[(cells[0], cells[1])] = (measured, int(cells[3]), cells[4], cells[5])
    return rows


def read(path):
    try:
        with open(path) as f:
            return f.read()
    except FileNotFoundError:
        return ""


def baseline_text(path):
    """(text, state): state is 'ok' or 'absent' (no such file at origin/main: empty baseline).
    Any git error exits non-zero."""
    if run(["git", "rev-parse", "--verify", "-q", "origin/main^{commit}"]).returncode != 0:
        raise SystemExit("git: origin/main is not known here (git fetch origin main)")
    t = run(["git", "ls-tree", "origin/main", "--", path])
    if t.returncode != 0:
        raise SystemExit(f"git ls-tree origin/main -- {path} failed: {t.stderr.strip()}")
    if not t.stdout.strip():
        return "", "absent"
    s = run(["git", "show", f"origin/main:{path}"])
    if s.returncode != 0:
        raise SystemExit(f"git show origin/main:{path} failed: {s.stderr.strip()}")
    return s.stdout, "ok"


def stamp():
    """(date, short commit) of the merge base of HEAD and origin/main, else of HEAD."""
    base = run(["git", "merge-base", "HEAD", "origin/main"])
    ref = base.stdout.strip() if base.returncode == 0 and base.stdout.strip() else "HEAD"
    date = run(["git", "show", "-s", "--format=%cs", ref]).stdout.strip()
    commit = run(["git", "rev-parse", "--short=7", ref]).stdout.strip()
    return date, commit


def provenance_ok(date, commit, cwd=ROOT, main="origin/main"):
    """The commit exists, is an ancestor of origin/main (a branch commit can vanish in a squash
    merge) and its committer date is the date column."""
    if not re.fullmatch(r"[0-9a-f]{7,40}", commit):
        return False
    if run(["git", "cat-file", "-e", f"{commit}^{{commit}}"], cwd).returncode != 0:
        return False
    if run(["git", "merge-base", "--is-ancestor", commit, main], cwd).returncode != 0:
        return False
    return run(["git", "show", "-s", "--format=%cs", commit], cwd).stdout.strip() == date


# Accepted rises of budgets: written by the generator below the table, so a regeneration keeps them
# (add an entry when the project manager accepts a rise; never remove one).
ACCEPTED = [
    "## Accepted rises",
    "",
    "### Scarb 2.20.1 and starknet-foundry 0.64.0 (FND-11, #293)",
    "",
    "Accepted by the project manager under D-144, 2026-10-02, cause: compiler (Scarb 2.20.1, D-180):",
    "",
    "- `enter`: +4 % to +6 % on its tests (`test_lifecycle::test_enter*`).",
    "- `set_build`: the worst case's call budget 8,501,927 → 9,100,742 (measured 8,667,373).",
    "- `grimworld_persistent`: rises up to +18.5 % (`test_lifecycle::test_rules_epoch_full_cycle_reads_fresh`).",
    "- `grimworld_ephemeral`: 24 rises, the largest +4.6 %.",
    "- The 14 rises on `create`, `create_adventurer`, `leave`, `travel_back` and `travel` (whole-test totals, setup and several calls included; test, before → after, %):",
    "  - `grimworld_ephemeral` `test_lifecycle::test_create_first_entry`: 31,790,192 → 32,575,012 (+2.5 %)",
    "  - `grimworld_ephemeral` `test_lifecycle::test_create_refusals`: 33,039,406 → 33,860,776 (+2.5 %)",
    "  - `grimworld_ephemeral` `test_lifecycle::test_create_reuses_the_slot`: 44,105,551 → 45,690,521 (+3.6 %)",
    "  - `grimworld_ephemeral` `test_lifecycle::test_create_sealed`: 25,877,196 → 26,583,366 (+2.7 %)",
    "  - `grimworld_ephemeral` `test_lifecycle::test_create_without_tasks`: 27,805,866 → 28,512,036 (+2.5 %)",
    "  - `grimworld_ephemeral` `test_lifecycle::test_leave_to_a_hub`: 33,228,136 → 34,221,056 (+3.0 %)",
    "  - `grimworld_ephemeral` `test_lifecycle::test_leave_to_a_location`: 39,224,907 → 41,012,107 (+4.6 %)",
    "  - `grimworld_ephemeral` `test_lifecycle::test_travel_back`: 31,536,609 → 32,510,779 (+3.1 %)",
    "  - `grimworld_persistent` `test_accounts::test_create_adventurer`: 23,924,760 → 24,718,590 (+3.3 %)",
    "  - `grimworld_persistent` `test_accounts::test_create_bad_profession_refused`: 9,286,710 → 9,660,880 (+4.0 %)",
    "  - `grimworld_persistent` `test_accounts::test_create_empty_name_refused`: 9,296,770 → 9,666,540 (+4.0 %)",
    "  - `grimworld_persistent` `test_accounts::test_create_no_free_slot_refused`: 19,504,540 → 20,381,910 (+4.5 %)",
    "  - `grimworld_persistent` `test_accounts::test_create_without_account_refused`: 7,654,840 → 7,954,210 (+3.9 %)",
    "  - `grimworld_persistent` `test_lifecycle::test_travel`: 35,630,367 → 37,310,737 (+4.7 %)",
    "",
    "### Fixture artefacts, not the tick's cost (CBT-05a, route (c), #334)",
    "",
    "Marked at the project manager's request, 2026-10-03. These five figures are not the cost of a tick: their "
    "fixtures place every goblin on one tile (CBT-02d's words carry no positions), so under route (c) each "
    "concluding activation's call to `ExecutorLibrary` carries all the goblins of the world, a state play cannot "
    "reach (one actor per tile). The tick's cost with the executor is ENG-01 §9.2's line: 26,422,703 a worst tick "
    "(17.98 × 1,469,435), the figure for ENG-07 and R-2. Measured (budget) at #334's head:",
    "",
    "- `grimworld_logic` `test_tick::test_cost_library_call`: 796,147,478 (835,954,852)",
    "- `grimworld_logic` `test_tick::test_cost_library_call_batch`: 803,951,145 (844,148,703)",
    "- `grimworld_logic` `test_tick::test_cost_library_call_kills`: 98,543,578 (103,470,757)",
    "- `grimworld_logic` `test_tick::test_cost_library_call_two_members`: 888,112,294 (932,517,909)",
    "- `grimworld_logic` `test_tick::test_library_matches_pipeline`: 833,920,536 (875,616,563)",
    "",
]


def render(rows, previous, ws, packages, keep_invalid):
    """({path or 'BUDGETS': text}, problems). A row whose measure and budget are unchanged keeps
    its date and commit if they verify; if not, it is stamped anew (write) or reported (check)."""
    problems, fresh = [], None
    for r in rows:
        old = previous.get((r["package"], r["test"]))
        if old and old[0] == r["measured"] and old[1] == r["budget"]:
            if provenance_ok(old[2], old[3]):
                r["date"], r["commit"] = old[2], old[3]
                continue
            if keep_invalid:
                problems.append(
                    f"{r['package']}::{r['test']}: date {old[2]} / commit {old[3]} do not verify "
                    f"(commit missing from the history, or its committer date differs)"
                )
                r["date"], r["commit"] = old[2], old[3]
                continue
        fresh = fresh or stamp()
        r["date"], r["commit"] = fresh
    budgets = [
        "# Gas budgets",
        "",
        MARKER,
        "",
        f"Source of truth for the cost budgets of `{ws}/` (docs/CAIRO.md §2, OPERATIONS §5). "
        "Written from a test run by `python3 scripts/gas_budgets.py`, checked in the CI by "
        "`--check`; never edit a figure by hand. Measured and budget are l2 gas as snforge "
        "reports them; budget = ceil(1.05 × measured). A fuzz test or a `#[test_case]` function "
        "has one budget for all its runs or cases: N = ceil(1.05 × the most expensive). A fuzz "
        "test's measured figure is the maximum l2 gas over its runs (fixed seed); each case of a "
        "`#[test_case]` is its own row; an `#[ignore]`d test is not measured and its row says "
        "`ignored`. Date and commit are those of the origin/main commit (merge base) the figures "
        "were measured on top of, an ancestor of origin/main, kept while the row's figures do "
        "not change.",
        "",
        "| Package | Test | Measured (l2 gas) | Budget (l2 gas) | Date | Commit |",
        "|---|---|---:|---:|---|---|",
    ]
    for r in rows:
        budgets.append(
            f"| {r['package']} | `{r['test']}` | {_m(r)} | {r['budget'] or '—'} "
            f"| {r['date']} | {r['commit']} |"
        )
    if ws.rstrip("/") == "contracts":
        budgets += [""] + ACCEPTED
    out = {"BUDGETS": "\n".join(budgets).rstrip("\n") + "\n"}
    for package, path in packages.items():
        mine = [r for r in rows if r["package"] == package]
        gas = [
            f"# Gas of {package}",
            "",
            MARKER,
            "",
            "Detail of every test of the package, from the same run as docs/BUDGETS.md. "
            "Headroom is the budget over the measure (a fuzz test's measure is the maximum over "
            "its runs).",
            "",
            "| Test | l2 gas | Budget | Headroom | l1 gas | l1 data gas | Date | Commit |",
            "|---|---:|---:|---:|---:|---:|---|---|",
        ]
        for r in mine:
            room, l1, l1d = "—", "—", "—"
            if r["measured"] is not None:
                l1, l1d = r["l1"], r["l1d"]
                if r["budget"] is not None:
                    room = f"{(r['budget'] - r['measured']) * 100 / r['measured']:.2f} %"
            gas.append(
                f"| `{r['test']}` | {_m(r)} | {r['budget'] or '—'} | {room} | {l1} | {l1d} "
                f"| {r['date']} | {r['commit']} |"
            )
        out[os.path.join(path, "GAS.md")] = "\n".join(gas) + "\n"
    return out, problems


def _m(r):
    return "ignored" if r["measured"] is None else r["measured"]


def report(rows, before):
    """The gas table of a REPORT.md, COMMON §7."""
    before = dict(before)
    lines = [
        "| Entrypoint or algorithm | Before | After | Budget | Note |",
        "|---|---:|---:|---:|---|",
    ]
    for r in rows:
        old = before.pop((r["package"], r["test"]), None)
        if old is None:
            b, note = "—", "new"
        elif old[0] is None or r["measured"] is None:
            b, note = ("—" if old[0] is None else str(old[0])), "ignored" if r["measured"] is None else "now measured"
        elif old[0] == r["measured"]:
            b, note = str(old[0]), "unchanged"
        else:
            b, note = str(old[0]), f"{(r['measured'] - old[0]) * 100 / old[0]:+.1f} %"
        if r.get("raised") is not None:
            note = f"raised: {r['raised']}; {note}"
        lines.append(
            f"| {r['package']}::{r['test']} | {b} | {_m(r) if r['measured'] is not None else '—'} "
            f"| {r['budget'] or '—'} | {note} |"
        )
    for (package, test), old in sorted(before.items()):
        lines.append(f"| {package}::{test} | {old[0] if old[0] is not None else '—'} | — | — | removed |")
    return "\n".join(lines) + "\n"


def collect(ws, output, baseline=None):
    packages = workspace_packages(ws)
    parsed = parse_output(output)
    rows, problems, notes = [], [], []
    for package, path in packages.items():
        mine = [(n, a, b, c) for p, n, a, b, c in parsed if p == package]
        r, p, n = analyse(package, package_decls(path), mine, baseline)
        rows += r
        problems += p
        notes += n
    rows.sort(key=lambda r: (r["package"], r["test"]))
    return rows, problems, notes, packages


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--report", action="store_true")
    mode.add_argument("--self-test", action="store_true")
    ap.add_argument("--workspace", default="contracts")
    ap.add_argument("--budgets", default="docs/BUDGETS.md")
    ap.add_argument("--no-lock", action="store_true")
    ap.add_argument("--from-output")
    args = ap.parse_args()
    os.chdir(ROOT)
    if args.self_test:
        suite = unittest.defaultTestLoader.loadTestsFromTestCase(SelfTest)
        sys.exit(0 if unittest.TextTestRunner(verbosity=1).run(suite).wasSuccessful() else 1)

    strict = args.check or args.report
    try:
        base_text, state = baseline_text(args.budgets)
    except SystemExit as e:
        if strict:
            raise
        print(f"gas: warning, no baseline ({e}): raises are not checked", file=sys.stderr)
        base_text, state = "", "unknown"
    before = parse_budgets(base_text)
    if state == "absent":
        print(f"gas: {args.budgets} is absent at origin/main: empty baseline", file=sys.stderr)
    baseline = {k: v[1] for k, v in before.items()} if state != "unknown" else None

    if args.from_output:
        text = read(args.from_output)
    else:
        cmd = ["snforge", "test", "--workspace", "--fuzzer-seed", "1"]
        if not args.no_lock:
            cmd = [os.path.join(ROOT, "scripts", "lock.sh"), "--heavy"] + cmd
        # D-176: a measured build is single-threaded, or the compiler's withdraw_gas placement follows
        # rayon's thread order and the figures differ between builds (docs/CAIRO.md §2).
        res = run(cmd, os.path.join(ROOT, args.workspace), {**os.environ, "RAYON_NUM_THREADS": "1"})
        text = res.stdout
        if res.returncode != 0:
            sys.stderr.write(text + res.stderr)
            raise SystemExit(f"snforge test failed (exit {res.returncode})")
    rows, problems, notes, packages = collect(args.workspace, text, baseline)
    if not rows:
        raise SystemExit("the run measured no test")
    for n in notes:
        print(f"gas: {n}")

    if args.report:
        if problems:
            for p in problems:
                print(f"gas report: {p}", file=sys.stderr)
            raise SystemExit(1)
        sys.stdout.write(report(rows, before))
        return

    files, more = render(rows, parse_budgets(read(args.budgets)), args.workspace, packages, args.check)
    problems += more
    files[args.budgets] = files.pop("BUDGETS")
    if args.check:
        for path, text in files.items():
            if read(path) != text:
                problems.append(f"{path} is stale against the run: rerun scripts/gas_budgets.py")
        for p in problems:
            print(f"gas check: {p}", file=sys.stderr)
        if problems:
            raise SystemExit(1)
        print(f"gas check: {len(rows)} tests, every budget is ceil(1.05 x measured) or lower, "
              f"{len(files)} files current")
        return

    for p in problems:
        print(f"gas: {p}", file=sys.stderr)
    for path, text in files.items():
        with open(path, "w") as f:
            f.write(text)
        print(f"wrote {path}")
    if problems:
        raise SystemExit(1)


# ---------------------------------------------------------------- self-test

SRC = """
use x::y;
#[cfg(test)]
mod tests {
    #[test]
    #[available_gas(
        l2_gas: 1050
    )]
    fn test_a() {}

    mod deep {
        #[test]
        fn test_a() {}          // same name, other module, no budget
    }
}

#[cfg(feature: 'nope')]
mod gated {
    #[test]
    fn test_g() {}

    #[test]
    #[available_gas(l2_gas: 7)]
    fn test_g_ok() {}
}

// gas: raised, the reveal now walks 3 chunks
#[available_gas(l2_gas: 2100)]
#[test_case(1, 2, 3)]
#[test_case(4, 5, 9)]
fn test_sum(a: u8, b: u8, c: u8) {}

#[test]
#[ignore]
fn test_slow() {}

#[test]
#[ignore]
#[available_gas(l2_gas: 5)]
fn test_slow_ok() { let s = 'a{b'; }
"""

OUT = """
Collected 5 test(s) from pkg package
Running 5 test(s) from src/
[PASS] pkg::tests::test_a (l1_gas: ~0, l1_data_gas: ~0, l2_gas: ~1000)
[PASS] pkg::tests::deep::test_a (l1_gas: ~0, l1_data_gas: ~0, l2_gas: ~1000)
[PASS] pkg_integrationtest::t::test_sum_1_2_3 (l1_gas: ~0, l1_data_gas: ~0, l2_gas: ~2000)
[PASS] pkg_integrationtest::t::test_sum_4_5_9 (l1_gas: ~0, l1_data_gas: ~0, l2_gas: ~2000)
[PASS] pkg::tests::fuzz_it (runs: 5, (l1_gas: {max: ~0, min: ~0, mean: ~0, std deviation: ~0}, \
l1_data_gas: {max: ~0, min: ~0, mean: ~0, std deviation: ~0}, \
l2_gas: {max: ~90360, min: ~78720, mean: ~86868, std deviation: ~4656}))
[IGNORE] pkg::tests::test_slow
"""


class SelfTest(unittest.TestCase):
    def setUp(self):
        self.decls = parse_source(SRC, ["t"], "f.cairo")
        self.keys = {d.key: d for d in self.decls}

    def test_snforge_lines(self):  # 2: fuzz max, plain, failure
        rows = parse_output(OUT)
        self.assertIn(("pkg", "tests::fuzz_it", 0, 0, 90360), rows)
        self.assertIn(("pkg", "t::test_sum_1_2_3", 0, 0, 2000), rows)
        with self.assertRaises(SystemExit):
            parse_output("Collected 1 test(s) from pkg package\n[FAIL] pkg::t (runs: 3)\n")

    def test_full_path_keys(self):  # 1
        self.assertIn("t::tests::test_a", self.keys)
        self.assertIn("t::tests::deep::test_a", self.keys)
        self.assertEqual(self.keys["t::tests::test_a"].budget, 1050)  # multiline attribute (5)
        self.assertIsNone(self.keys["t::tests::deep::test_a"].budget)

    def test_same_name_other_module_is_rejected(self):  # 1
        rows, problems, _ = analyse("pkg", self.decls, [("t::tests::test_a", 0, 0, 1000),
                                                        ("t::tests::deep::test_a", 0, 0, 1000)])
        self.assertTrue(any("t::tests::deep::test_a: no #[available_gas" in p for p in problems))
        self.assertFalse(any("t::tests::test_a:" in p for p in problems))

    def test_unmeasured_twin_is_not_hidden(self):  # 1
        _, problems, _ = analyse("pkg", self.decls, [("t::tests::test_a", 0, 0, 1000)])
        self.assertTrue(any("deep::test_a: declared #[test] but not measured" in p for p in problems))

    def test_cases_map_to_source(self):  # 2
        rows, problems, _ = analyse("pkg", self.decls, [("t::test_sum_1_2_3", 0, 0, 2000),
                                                        ("t::test_sum_4_5_9", 0, 0, 2000)])
        self.assertEqual([r["test"] for r in rows if "test_sum" in r["test"]],
                         ["t::test_sum_1_2_3", "t::test_sum_4_5_9"])
        self.assertFalse(any("test_sum" in p for p in problems))
        _, problems, _ = analyse("pkg", self.decls, [("t::test_sum_1_2_3", 0, 0, 2000)])
        self.assertTrue(any("2 #[test_case] declared, 1 measured" in p for p in problems))

    def test_ignored_needs_a_budget(self):  # 3
        rows, problems, _ = analyse("pkg", self.decls, [])
        self.assertTrue(any("t::test_slow: no #[available_gas" in p for p in problems))
        ok = [r for r in rows if r["test"] == "t::test_slow_ok"][0]
        self.assertIsNone(ok["measured"])
        self.assertEqual(ok["budget"], 5)

    def test_cfg_gated_needs_a_budget(self):  # 5
        _, problems, notes = analyse("pkg", self.decls, [])
        self.assertTrue(any("t::gated::test_g: no #[available_gas" in p for p in problems))
        self.assertFalse(any("test_g_ok" in p for p in problems))
        self.assertIn("pkg::t::gated::test_g_ok: cfg-gated, not measured "
                      "(only its budget attribute is checked)", notes)

    def test_provenance_needs_an_ancestor_of_main(self):  # 6
        import tempfile
        from unittest import mock

        # The fixture's git, and provenance_ok's, see none of git's repository variables (FND-17: run from
        # a hook in a linked worktree, GIT_DIR made `git init` rewrite the real repository): only its own
        # temporary repository, and discovery never climbs above it.
        local = {"GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_OBJECT_DIRECTORY",
                 "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_PREFIX", "GIT_COMMON_DIR",
                 "GIT_IMPLICIT_WORK_TREE", "GIT_GRAFT_FILE", "GIT_NO_REPLACE_OBJECTS",
                 "GIT_REPLACE_REF_BASE", "GIT_SHALLOW_FILE", "GIT_NAMESPACE"}
        clean = {k: v for k, v in os.environ.items() if k not in local and not k.startswith("GIT_CONFIG")}
        with tempfile.TemporaryDirectory() as d, mock.patch.dict(os.environ, clean, clear=True):
            os.environ["GIT_CEILING_DIRECTORIES"] = os.path.dirname(os.path.realpath(d))

            def git(*a):
                return subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", *a],
                                      cwd=d, capture_output=True, text=True, check=True,
                                      env=dict(os.environ)).stdout.strip()

            git("init", "-q", "-b", "main")
            git("commit", "-q", "--allow-empty", "-m", "a")
            on_main = git("rev-parse", "--short=7", "HEAD")
            git("checkout", "-q", "-b", "branch")
            git("commit", "-q", "--allow-empty", "-m", "b")
            on_branch = git("rev-parse", "--short=7", "HEAD")
            date = git("show", "-s", "--format=%cs", "HEAD")
            self.assertTrue(provenance_ok(date, on_main, d, "main"))
            self.assertFalse(provenance_ok(date, on_branch, d, "main"))  # date matches, not in main
            self.assertFalse(provenance_ok("1999-01-01", on_main, d, "main"))
            self.assertFalse(provenance_ok(date, "deadbee", d, "main"))

    def test_raise_needs_a_reason(self):  # 4
        d = self.keys["t::test_sum"]
        self.assertEqual(d.reason, "the reveal now walks 3 chunks")
        rows, problems, _ = analyse("pkg", self.decls, [("t::test_sum_1_2_3", 0, 0, 2000),
                                                        ("t::test_sum_4_5_9", 0, 0, 2000)],
                                    {("pkg", "t::test_sum_1_2_3"): 1000})
        self.assertFalse(any("test_sum" in p for p in problems))
        self.assertEqual([r["raised"] for r in rows if "raised" in r],
                         ["the reveal now walks 3 chunks"])
        _, problems, _ = analyse("pkg", self.decls, [("t::tests::test_a", 0, 0, 1000),
                                                     ("t::tests::deep::test_a", 0, 0, 1000)],
                                 {("pkg", "t::tests::test_a"): 500})
        self.assertTrue(any("budget raised 500 -> 1050" in p for p in problems))

    def test_loose(self):
        _, problems, _ = analyse("pkg", self.decls, [("t::tests::test_a", 0, 0, 500)])
        self.assertTrue(any("t::tests::test_a: budget 1050 is loose" in p for p in problems))


if __name__ == "__main__":
    main()
