//! Generated by gen_tables.py: do not edit by hand.

/// The first bit of each row of a hexagonal chunk.
pub const FIRST: [u8; 17] = [
    0x0, 0xb, 0x17, 0x24, 0x32, 0x41, 0x51, 0x62, 0x74, 0x87, 0x99, 0xaa, 0xba, 0xc9, 0xd7, 0xe4,
    0xf0,
];

/// The lowest axial `q` of each row.
pub const QLO: [u8; 17] = [
    0x8, 0x7, 0x6, 0x5, 0x4, 0x3, 0x2, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
];

/// The highest axial `q` of each row.
pub const QHI: [u8; 17] = [
    0x12, 0x12, 0x12, 0x12, 0x12, 0x12, 0x12, 0x12, 0x12, 0x11, 0x10, 0xf, 0xe, 0xd, 0xc, 0xb, 0xa,
];

/// The tile of each bit: `q + 32 r`.
pub const TILE: [u16; 251] = [
    0x8, 0x9, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, 0x10, 0x11, 0x12, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c,
    0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f,
    0x50, 0x51, 0x52, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f, 0x70, 0x71,
    0x72, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92,
    0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2,
    0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf, 0xd0, 0xd1,
    0xd2, 0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb, 0xec, 0xed, 0xee, 0xef,
    0xf0, 0xf1, 0xf2, 0x100, 0x101, 0x102, 0x103, 0x104, 0x105, 0x106, 0x107, 0x108, 0x109, 0x10a,
    0x10b, 0x10c, 0x10d, 0x10e, 0x10f, 0x110, 0x111, 0x112, 0x120, 0x121, 0x122, 0x123, 0x124,
    0x125, 0x126, 0x127, 0x128, 0x129, 0x12a, 0x12b, 0x12c, 0x12d, 0x12e, 0x12f, 0x130, 0x131,
    0x140, 0x141, 0x142, 0x143, 0x144, 0x145, 0x146, 0x147, 0x148, 0x149, 0x14a, 0x14b, 0x14c,
    0x14d, 0x14e, 0x14f, 0x150, 0x160, 0x161, 0x162, 0x163, 0x164, 0x165, 0x166, 0x167, 0x168,
    0x169, 0x16a, 0x16b, 0x16c, 0x16d, 0x16e, 0x16f, 0x180, 0x181, 0x182, 0x183, 0x184, 0x185,
    0x186, 0x187, 0x188, 0x189, 0x18a, 0x18b, 0x18c, 0x18d, 0x18e, 0x1a0, 0x1a1, 0x1a2, 0x1a3,
    0x1a4, 0x1a5, 0x1a6, 0x1a7, 0x1a8, 0x1a9, 0x1aa, 0x1ab, 0x1ac, 0x1ad, 0x1c0, 0x1c1, 0x1c2,
    0x1c3, 0x1c4, 0x1c5, 0x1c6, 0x1c7, 0x1c8, 0x1c9, 0x1ca, 0x1cb, 0x1cc, 0x1e0, 0x1e1, 0x1e2,
    0x1e3, 0x1e4, 0x1e5, 0x1e6, 0x1e7, 0x1e8, 0x1e9, 0x1ea, 0x1eb, 0x200, 0x201, 0x202, 0x203,
    0x204, 0x205, 0x206, 0x207, 0x208, 0x209, 0x20a,
];

/// Per row of a chunk, one lookup: `(FIRST[r], QHI[r], QLO[r])`.
pub const ROW: [(u8, u8, u8); 17] = [
    (0, 18, 8), (11, 18, 7), (23, 18, 6), (36, 18, 5), (50, 18, 4), (65, 18, 3), (81, 18, 2),
    (98, 18, 1), (116, 18, 0), (135, 17, 0), (153, 16, 0), (170, 15, 0), (186, 14, 0), (201, 13, 0),
    (215, 12, 0), (228, 11, 0), (240, 10, 0),
];

/// `2^k - 1` in one limb, `k` in `0..=128`.
pub const BELOW128: [u128; 129] = [
    0x0, 0x1, 0x3, 0x7, 0xf, 0x1f, 0x3f, 0x7f, 0xff, 0x1ff, 0x3ff, 0x7ff, 0xfff, 0x1fff, 0x3fff,
    0x7fff, 0xffff, 0x1ffff, 0x3ffff, 0x7ffff, 0xfffff, 0x1fffff, 0x3fffff, 0x7fffff, 0xffffff,
    0x1ffffff, 0x3ffffff, 0x7ffffff, 0xfffffff, 0x1fffffff, 0x3fffffff, 0x7fffffff, 0xffffffff,
    0x1ffffffff, 0x3ffffffff, 0x7ffffffff, 0xfffffffff, 0x1fffffffff, 0x3fffffffff, 0x7fffffffff,
    0xffffffffff, 0x1ffffffffff, 0x3ffffffffff, 0x7ffffffffff, 0xfffffffffff, 0x1fffffffffff,
    0x3fffffffffff, 0x7fffffffffff, 0xffffffffffff, 0x1ffffffffffff, 0x3ffffffffffff,
    0x7ffffffffffff, 0xfffffffffffff, 0x1fffffffffffff, 0x3fffffffffffff, 0x7fffffffffffff,
    0xffffffffffffff, 0x1ffffffffffffff, 0x3ffffffffffffff, 0x7ffffffffffffff, 0xfffffffffffffff,
    0x1fffffffffffffff, 0x3fffffffffffffff, 0x7fffffffffffffff, 0xffffffffffffffff,
    0x1ffffffffffffffff, 0x3ffffffffffffffff, 0x7ffffffffffffffff, 0xfffffffffffffffff,
    0x1fffffffffffffffff, 0x3fffffffffffffffff, 0x7fffffffffffffffff, 0xffffffffffffffffff,
    0x1ffffffffffffffffff, 0x3ffffffffffffffffff, 0x7ffffffffffffffffff, 0xfffffffffffffffffff,
    0x1fffffffffffffffffff, 0x3fffffffffffffffffff, 0x7fffffffffffffffffff, 0xffffffffffffffffffff,
    0x1ffffffffffffffffffff, 0x3ffffffffffffffffffff, 0x7ffffffffffffffffffff,
    0xfffffffffffffffffffff, 0x1fffffffffffffffffffff, 0x3fffffffffffffffffffff,
    0x7fffffffffffffffffffff, 0xffffffffffffffffffffff, 0x1ffffffffffffffffffffff,
    0x3ffffffffffffffffffffff, 0x7ffffffffffffffffffffff, 0xfffffffffffffffffffffff,
    0x1fffffffffffffffffffffff, 0x3fffffffffffffffffffffff, 0x7fffffffffffffffffffffff,
    0xffffffffffffffffffffffff, 0x1ffffffffffffffffffffffff, 0x3ffffffffffffffffffffffff,
    0x7ffffffffffffffffffffffff, 0xfffffffffffffffffffffffff, 0x1fffffffffffffffffffffffff,
    0x3fffffffffffffffffffffffff, 0x7fffffffffffffffffffffffff, 0xffffffffffffffffffffffffff,
    0x1ffffffffffffffffffffffffff, 0x3ffffffffffffffffffffffffff, 0x7ffffffffffffffffffffffffff,
    0xfffffffffffffffffffffffffff, 0x1fffffffffffffffffffffffffff, 0x3fffffffffffffffffffffffffff,
    0x7fffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffff, 0x1ffffffffffffffffffffffffffff,
    0x3ffffffffffffffffffffffffffff, 0x7ffffffffffffffffffffffffffff,
    0xfffffffffffffffffffffffffffff, 0x1fffffffffffffffffffffffffffff,
    0x3fffffffffffffffffffffffffffff, 0x7fffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffff, 0x1ffffffffffffffffffffffffffffff,
    0x3ffffffffffffffffffffffffffffff, 0x7ffffffffffffffffffffffffffffff,
    0xfffffffffffffffffffffffffffffff, 0x1fffffffffffffffffffffffffffffff,
    0x3fffffffffffffffffffffffffffffff, 0x7fffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff,
];

/// The low limb of `2^k - 1`, the bits below `k`, for `k` in `0..=251`.
pub const BELOW_LOW: [u128; 252] = [
    0x0, 0x1, 0x3, 0x7, 0xf, 0x1f, 0x3f, 0x7f, 0xff, 0x1ff, 0x3ff, 0x7ff, 0xfff, 0x1fff, 0x3fff,
    0x7fff, 0xffff, 0x1ffff, 0x3ffff, 0x7ffff, 0xfffff, 0x1fffff, 0x3fffff, 0x7fffff, 0xffffff,
    0x1ffffff, 0x3ffffff, 0x7ffffff, 0xfffffff, 0x1fffffff, 0x3fffffff, 0x7fffffff, 0xffffffff,
    0x1ffffffff, 0x3ffffffff, 0x7ffffffff, 0xfffffffff, 0x1fffffffff, 0x3fffffffff, 0x7fffffffff,
    0xffffffffff, 0x1ffffffffff, 0x3ffffffffff, 0x7ffffffffff, 0xfffffffffff, 0x1fffffffffff,
    0x3fffffffffff, 0x7fffffffffff, 0xffffffffffff, 0x1ffffffffffff, 0x3ffffffffffff,
    0x7ffffffffffff, 0xfffffffffffff, 0x1fffffffffffff, 0x3fffffffffffff, 0x7fffffffffffff,
    0xffffffffffffff, 0x1ffffffffffffff, 0x3ffffffffffffff, 0x7ffffffffffffff, 0xfffffffffffffff,
    0x1fffffffffffffff, 0x3fffffffffffffff, 0x7fffffffffffffff, 0xffffffffffffffff,
    0x1ffffffffffffffff, 0x3ffffffffffffffff, 0x7ffffffffffffffff, 0xfffffffffffffffff,
    0x1fffffffffffffffff, 0x3fffffffffffffffff, 0x7fffffffffffffffff, 0xffffffffffffffffff,
    0x1ffffffffffffffffff, 0x3ffffffffffffffffff, 0x7ffffffffffffffffff, 0xfffffffffffffffffff,
    0x1fffffffffffffffffff, 0x3fffffffffffffffffff, 0x7fffffffffffffffffff, 0xffffffffffffffffffff,
    0x1ffffffffffffffffffff, 0x3ffffffffffffffffffff, 0x7ffffffffffffffffffff,
    0xfffffffffffffffffffff, 0x1fffffffffffffffffffff, 0x3fffffffffffffffffffff,
    0x7fffffffffffffffffffff, 0xffffffffffffffffffffff, 0x1ffffffffffffffffffffff,
    0x3ffffffffffffffffffffff, 0x7ffffffffffffffffffffff, 0xfffffffffffffffffffffff,
    0x1fffffffffffffffffffffff, 0x3fffffffffffffffffffffff, 0x7fffffffffffffffffffffff,
    0xffffffffffffffffffffffff, 0x1ffffffffffffffffffffffff, 0x3ffffffffffffffffffffffff,
    0x7ffffffffffffffffffffffff, 0xfffffffffffffffffffffffff, 0x1fffffffffffffffffffffffff,
    0x3fffffffffffffffffffffffff, 0x7fffffffffffffffffffffffff, 0xffffffffffffffffffffffffff,
    0x1ffffffffffffffffffffffffff, 0x3ffffffffffffffffffffffffff, 0x7ffffffffffffffffffffffffff,
    0xfffffffffffffffffffffffffff, 0x1fffffffffffffffffffffffffff, 0x3fffffffffffffffffffffffffff,
    0x7fffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffff, 0x1ffffffffffffffffffffffffffff,
    0x3ffffffffffffffffffffffffffff, 0x7ffffffffffffffffffffffffffff,
    0xfffffffffffffffffffffffffffff, 0x1fffffffffffffffffffffffffffff,
    0x3fffffffffffffffffffffffffffff, 0x7fffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffff, 0x1ffffffffffffffffffffffffffffff,
    0x3ffffffffffffffffffffffffffffff, 0x7ffffffffffffffffffffffffffffff,
    0xfffffffffffffffffffffffffffffff, 0x1fffffffffffffffffffffffffffffff,
    0x3fffffffffffffffffffffffffffffff, 0x7fffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff,
];

/// The high limb of `2^k - 1`.
pub const BELOW_HIGH: [u128; 252] = [
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x3, 0x7, 0xf,
    0x1f, 0x3f, 0x7f, 0xff, 0x1ff, 0x3ff, 0x7ff, 0xfff, 0x1fff, 0x3fff, 0x7fff, 0xffff, 0x1ffff,
    0x3ffff, 0x7ffff, 0xfffff, 0x1fffff, 0x3fffff, 0x7fffff, 0xffffff, 0x1ffffff, 0x3ffffff,
    0x7ffffff, 0xfffffff, 0x1fffffff, 0x3fffffff, 0x7fffffff, 0xffffffff, 0x1ffffffff, 0x3ffffffff,
    0x7ffffffff, 0xfffffffff, 0x1fffffffff, 0x3fffffffff, 0x7fffffffff, 0xffffffffff, 0x1ffffffffff,
    0x3ffffffffff, 0x7ffffffffff, 0xfffffffffff, 0x1fffffffffff, 0x3fffffffffff, 0x7fffffffffff,
    0xffffffffffff, 0x1ffffffffffff, 0x3ffffffffffff, 0x7ffffffffffff, 0xfffffffffffff,
    0x1fffffffffffff, 0x3fffffffffffff, 0x7fffffffffffff, 0xffffffffffffff, 0x1ffffffffffffff,
    0x3ffffffffffffff, 0x7ffffffffffffff, 0xfffffffffffffff, 0x1fffffffffffffff, 0x3fffffffffffffff,
    0x7fffffffffffffff, 0xffffffffffffffff, 0x1ffffffffffffffff, 0x3ffffffffffffffff,
    0x7ffffffffffffffff, 0xfffffffffffffffff, 0x1fffffffffffffffff, 0x3fffffffffffffffff,
    0x7fffffffffffffffff, 0xffffffffffffffffff, 0x1ffffffffffffffffff, 0x3ffffffffffffffffff,
    0x7ffffffffffffffffff, 0xfffffffffffffffffff, 0x1fffffffffffffffffff, 0x3fffffffffffffffffff,
    0x7fffffffffffffffffff, 0xffffffffffffffffffff, 0x1ffffffffffffffffffff,
    0x3ffffffffffffffffffff, 0x7ffffffffffffffffffff, 0xfffffffffffffffffffff,
    0x1fffffffffffffffffffff, 0x3fffffffffffffffffffff, 0x7fffffffffffffffffffff,
    0xffffffffffffffffffffff, 0x1ffffffffffffffffffffff, 0x3ffffffffffffffffffffff,
    0x7ffffffffffffffffffffff, 0xfffffffffffffffffffffff, 0x1fffffffffffffffffffffff,
    0x3fffffffffffffffffffffff, 0x7fffffffffffffffffffffff, 0xffffffffffffffffffffffff,
    0x1ffffffffffffffffffffffff, 0x3ffffffffffffffffffffffff, 0x7ffffffffffffffffffffffff,
    0xfffffffffffffffffffffffff, 0x1fffffffffffffffffffffffff, 0x3fffffffffffffffffffffffff,
    0x7fffffffffffffffffffffffff, 0xffffffffffffffffffffffffff, 0x1ffffffffffffffffffffffffff,
    0x3ffffffffffffffffffffffffff, 0x7ffffffffffffffffffffffffff, 0xfffffffffffffffffffffffffff,
    0x1fffffffffffffffffffffffffff, 0x3fffffffffffffffffffffffffff, 0x7fffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffff, 0x1ffffffffffffffffffffffffffff,
    0x3ffffffffffffffffffffffffffff, 0x7ffffffffffffffffffffffffffff,
    0xfffffffffffffffffffffffffffff, 0x1fffffffffffffffffffffffffffff,
    0x3fffffffffffffffffffffffffffff, 0x7fffffffffffffffffffffffffffff,
    0xffffffffffffffffffffffffffffff, 0x1ffffffffffffffffffffffffffffff,
    0x3ffffffffffffffffffffffffffffff, 0x7ffffffffffffffffffffffffffffff,
];

/// The interior of the 15 x 16 window, low limb (its ring is wall).
pub const WINDOW_INTERIOR_LOW: u128 = 0xfe7ffcfff9fff3ffe7ffcfff9fff0000;

/// The interior of the 15 x 16 window, high limb.
pub const WINDOW_INTERIOR_HIGH: u128 = 0xfff9fff3ffe7ffcfff9fff3f;

/// Interior of a 15 x 15 chunk, 13 x 13.
pub const RECT_INTERIOR: felt252 = 0x1fff3ffe7ffcfff9fff3ffe7ffcfff9fff3ffe7ffcfff9fff0000;

/// Row 7 and column 7 of the interior.
pub const RECT_SPINE: felt252 = 0x4000800100020004000807ffc02000400080010002000400000;

/// Ring column x = 0, corners excluded.
pub const RECT_COL_EAST: felt252 = 0x8001000200040008001000200040008001000200040008000;

/// Ring column x = 14, corners excluded.
pub const RECT_COL_WEST: felt252 = 0x20004000800100020004000800100020004000800100020000000;

/// Ring row y = 0, corners excluded.
pub const RECT_ROW_SOUTH: felt252 = 0x3ffe;

/// Ring row y = 14, corners excluded.
pub const RECT_ROW_NORTH: felt252 = 0xfff80000000000000000000000000000000000000000000000000000;

/// Rows of a chunk on even global rows: `[0]` even start, `[1]` odd (the parity flag).
pub const RECT_EVEN: [felt252; 2] = [
    0x1fffc0007fff0001fffc0007fff0001fffc0007fff0001fffc0007fff,
    0x3fff8000fffe0003fff8000fffe0003fff8000fffe0003fff8000,
];

/// Rows 0 and 1 of a chunk.
pub const RECT_LOW30: u128 = 0x3fffffff;

/// 2^(W - 1).
pub const RECT_UP: felt252 = 0x4000;

/// 2^-(W + 1).
pub const RECT_DOWN: felt252 = 0x7fff80000000010ffef00000000000000000000000000000000000000000001;

/// From an opening at x = 0 to x = 1..6 of its row.
pub const RECT_LINE_EAST: felt252 = 0x7e;

/// From an opening at x = 14 to x = 8..13 of its row.
pub const RECT_LINE_WEST: felt252 =
    0x20000000000000440000000000000000000000000000000000000000000001;

/// From an opening at y = 0 to y = 1..6 of its column.
pub const RECT_LINE_SOUTH: felt252 = 0x40008001000200040008000;

/// From an opening at y = 14 to y = 8..13 of its column.
pub const RECT_LINE_NORTH: felt252 =
    0x7ffefffdfffc0107fdcffb9ff77feeffddffbc0000000000000000000000001;

/// Interior tiles of half S (rows 0-9).
pub const S_INTERIOR: u256 = u256 {
    low: 0xffe1fff83ffe07ff80ffe01ff8000000, high: 0xffff3fffe7fff8f,
};

/// Interior tiles of half N (rows 7-16).
pub const N_INTERIOR: u256 = u256 { low: 0x7ff81fff07ffe1fffc7fff9ffff3fffc, high: 0x7fe01ffc0 };

/// The spine in S: row 8, q = 9 and q + r = 17 through the centre (9, 8).
pub const S_SPINE: u256 = u256 { low: 0x28000900022000840020800810000000, high: 0x1803fffe00c000 };

/// The spine in N.
pub const N_SPINE: u256 = u256 { low: 0x8400110002400050000c01ffff00600, high: 0x204004100 };

/// 2^-18.
pub const INV_18: felt252 = 0x7fffe0000000010fffbc0000000000000000000000000000000000000000001;

/// 2^-19.
pub const INV_19: felt252 = 0x7ffff0000000010fffde0000000000000000000000000000000000000000001;

/// The centre (9, 8) in S.
pub const S_CENTRE: u8 = 0xa1;

/// The centre (9, 8) in N.
pub const N_CENTRE: u8 = 0x1c;

/// The first row of a half.
pub const LOW19: u128 = 0x7ffff;

/// From (q, 0) to (q, 1..7): up 7 rows.
pub const LINE_UP: felt252 = 0x2000040000800010000200004000080000;

/// From (q, 16) to (q, 15..9): down 7 rows.
pub const LINE_DOWN: felt252 = 0x7fffeffffe0000cfffd5fffabfff57ffeafffddfffbbfff7800000000000001;

/// From q = 18 or q + r = 26 to the 8 tiles of lower q, to the spine.
pub const LINE_LOWER_Q: felt252 = 0x8000000000000110000000000000000000000000000000000000000000001;

/// From q = 0 or q + r = 8 to the 8 tiles of higher q, to the spine.
pub const LINE_HIGHER_Q: felt252 = 0x1fe;

/// Rows 7-8 of S.
pub const S_ROWS78: u256 = u256 { low: 0x0, high: 0x7ffffffffe0 };

/// Rows 7-8 of N.
pub const N_ROWS78: u256 = u256 { low: 0x3fffffffff, high: 0x0 };

/// Row 9 of S.
pub const S_ROW9: u256 = u256 { low: 0x0, high: 0x3ffff80000000000 };

/// Row 9 of N.
pub const N_ROW9: u256 = u256 { low: 0x1ffffc000000000, high: 0x0 };

/// 2^133: N to S.
pub const SYNC_UP: felt252 = 0x2000000000000000000000000000000000;

/// 2^-133: S to N.
pub const SYNC_DOWN: felt252 = 0x800000000000010ffffffffffffffffffbfffffffffffff7800000000000001;

/// Side minus_u: the half bits of its non-corner tiles.
pub const SIDE_MINUS_U: [u8; 9] = [0x9, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, 0x10, 0x11];

/// Side plus_u: the half bits of its non-corner tiles.
pub const SIDE_PLUS_U: [u8; 9] = [0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3, 0xb4];

/// Side plus_r: the half bits of its non-corner tiles.
pub const SIDE_PLUS_R: [u8; 7] = [0x25, 0x38, 0x4b, 0x5e, 0x71, 0x84, 0x97];

/// Side minus_r: the half bits of its non-corner tiles.
pub const SIDE_MINUS_R: [u8; 7] = [0x26, 0x39, 0x4c, 0x5f, 0x72, 0x85, 0x98];

/// Side plus_ur: the half bits of its non-corner tiles.
pub const SIDE_PLUS_UR: [u8; 7] = [0x37, 0x49, 0x5b, 0x6d, 0x7f, 0x91, 0xa3];

/// Side minus_ur: the half bits of its non-corner tiles.
pub const SIDE_MINUS_UR: [u8; 7] = [0x1a, 0x2c, 0x3e, 0x50, 0x62, 0x74, 0x86];

/// The neighbour -T_U's facing side (its row 16), dense.
pub const COPY_MINUS_U_MASK: u256 = u256 { low: 0x0, high: 0x3fe0000000000000000000000000000 };

/// Its row 16 onto our row 0 in S.
pub const COPY_MINUS_U_SHIFT: felt252 = 0x8800000000000120fffffffffffffffffffffffffffffffff80000;

/// The neighbour +T_U's facing side (its row 0), dense.
pub const COPY_PLUS_U_MASK: u256 = u256 { low: 0x3fe, high: 0x0 };

/// Its row 0 onto our row 16 in N.
pub const COPY_PLUS_U_SHIFT: felt252 = 0x8000000000000000000000000000000000000000000;

/// Side plus_r copied: (the neighbour's dense bit, our half bit).
pub const GATHER_PLUS_R: [(u8, u8); 7] = [
    (135, 37), (153, 56), (170, 75), (186, 94), (201, 113), (215, 132), (228, 151),
];

/// Side minus_r copied: (the neighbour's dense bit, our half bit).
pub const GATHER_MINUS_R: [(u8, u8); 7] = [
    (22, 38), (35, 57), (49, 76), (64, 95), (80, 114), (97, 133), (115, 152),
];

/// Side plus_ur copied: (the neighbour's dense bit, our half bit).
pub const GATHER_PLUS_UR: [(u8, u8); 7] = [
    (11, 55), (23, 73), (36, 91), (50, 109), (65, 127), (81, 145), (98, 163),
];

/// Side minus_ur copied: (the neighbour's dense bit, our half bit).
pub const GATHER_MINUS_UR: [(u8, u8); 7] = [
    (152, 26), (169, 44), (185, 62), (200, 80), (214, 98), (227, 116), (239, 134),
];

/// Packing: per row `(mask_low, mask_high, shift)` from its half (S rows 0-8, N 9-16).
pub const PACK: [(u128, u128, felt252); 17] = [
    (0x7ff00, 0x0, 0x7f8000000000010ef0000000000000000000000000000000000000000000001),
    (0x3ffc000000, 0x0, 0x7fff00000000010ffde00000000000000000000000000000000000000000001),
    (0x1fff00000000000, 0x0, 0x7ffffc000000010ffff78000000000000000000000000000000000000000001),
    (0xfffc000000000000000, 0x0, 0x7fffffe00000010fffffbc00000000000000000000000000000000000000001),
    (
        0x7fff00000000000000000000,
        0x0,
        0x7ffffffe0000010ffffffbc0000000000000000000000000000000000000001,
    ),
    (
        0x3fffc000000000000000000000000,
        0x0,
        0x7fffffffc000010fffffff78000000000000000000000000000000000000001,
    ),
    (
        0xfff00000000000000000000000000000,
        0x1f,
        0x7ffffffff000010fffffffde000000000000000000000000000000000000001,
    ),
    (0x0, 0xffffc0, 0x7ffffffff800010fffffffef000000000000000000000000000000000000001),
    (0x0, 0x7ffff000000, 0x7ffffffff800010fffffffef000000000000000000000000000000000000001),
    (0xffffc000000000, 0x0, 0x2000000000000000000000000),
    (0x3fffe00000000000000, 0x0, 0x1000000000000000000000000),
    (0xffff0000000000000000000, 0x0, 0x400000000000000000000000),
    (0x3fff800000000000000000000000, 0x0, 0x80000000000000000000000),
    (0xfffc0000000000000000000000000000, 0x0, 0x8000000000000000000000),
    (0x0, 0x3ffe0, 0x400000000000000000000), (0x0, 0xfff000000, 0x10000000000000000000),
    (0x0, 0x3ff80000000000, 0x200000000000000000),
];

/// Side minus_u: its non-corner tiles, dense.
pub const DENSE_MINUS_U: [u8; 9] = [0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9];

/// Side minus_u: the neighbour's facing tiles, dense (its frame).
pub const FACING_MINUS_U: [u8; 9] = [0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9];

/// Side plus_u: its non-corner tiles, dense.
pub const DENSE_PLUS_U: [u8; 9] = [0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9];

/// Side plus_u: the neighbour's facing tiles, dense (its frame).
pub const FACING_PLUS_U: [u8; 9] = [0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9];

/// Side plus_r: its non-corner tiles, dense.
pub const DENSE_PLUS_R: [u8; 7] = [0x16, 0x23, 0x31, 0x40, 0x50, 0x61, 0x73];

/// Side plus_r: the neighbour's facing tiles, dense (its frame).
pub const FACING_PLUS_R: [u8; 7] = [0x87, 0x99, 0xaa, 0xba, 0xc9, 0xd7, 0xe4];

/// Side minus_r: its non-corner tiles, dense.
pub const DENSE_MINUS_R: [u8; 7] = [0x87, 0x99, 0xaa, 0xba, 0xc9, 0xd7, 0xe4];

/// Side minus_r: the neighbour's facing tiles, dense (its frame).
pub const FACING_MINUS_R: [u8; 7] = [0x16, 0x23, 0x31, 0x40, 0x50, 0x61, 0x73];

/// Side plus_ur: its non-corner tiles, dense.
pub const DENSE_PLUS_UR: [u8; 7] = [0x98, 0xa9, 0xb9, 0xc8, 0xd6, 0xe3, 0xef];

/// Side plus_ur: the neighbour's facing tiles, dense (its frame).
pub const FACING_PLUS_UR: [u8; 7] = [0xb, 0x17, 0x24, 0x32, 0x41, 0x51, 0x62];

/// Side minus_ur: its non-corner tiles, dense.
pub const DENSE_MINUS_UR: [u8; 7] = [0xb, 0x17, 0x24, 0x32, 0x41, 0x51, 0x62];

/// Side minus_ur: the neighbour's facing tiles, dense (its frame).
pub const FACING_MINUS_UR: [u8; 7] = [0x98, 0xa9, 0xb9, 0xc8, 0xd6, 0xe3, 0xef];
