//! Generated by boards.py from model.py: do not edit by hand.

/// Deepest winding board found from local (7, 7): eccentricity 88, 102 walkable tiles.
pub const DEEP_TERRAIN: felt252 = 0xee392b53576150cd5c85ad304a4d94a8a955d2bc65834ada8d770000;
/// Its 8 goblins, on the 8 farthest tiles: the nearest closes the corridor for the others.
pub const DEEP_GOBLINS: [u8; 8] = [20, 21, 22, 24, 35, 36, 38, 39];
/// Layers of the unlimited flood on it, start included.
pub const DEEP_LAYERS: u32 = 89;
/// Deepest winding board found from local (7, 8): eccentricity 91.
pub const DEEP_EVEN_TERRAIN: felt252 = 0xdef95312d1a422cbb414572ea262acb4b15b428ae5e848568fdb0000;
pub const DEEP_EVEN_LAYERS: u32 = 92;

/// Worst case of the tick under D-127 (D-127, ADR-0006 §4): winding (unlimited depth 20),
/// 8 goblins reached at distances [13, 3, 15, 4, 3, 2, 5, 7], all stepping, 5 steps crossing a
/// chunk boundary when the window's offsets in its chunks are dx = 7, dy = 7.
pub const CAPPED_TERRAIN: felt252 = 0xfff9fff2ffe6ffcbff97ff2ffe6ffcbff9bff2f866f7cc1f9fff0000;
pub const CAPPED_GOBLINS: [u8; 8] = [21, 67, 117, 124, 125, 126, 188, 206];
pub const CAPPED_DISTANCES: [u8; 8] = [13, 3, 15, 4, 3, 2, 5, 7];
pub const CAPPED_MOVES: [u8; 8] = [20, 81, 133, 109, 110, 111, 172, 191];
pub const CAPPED_DX: u8 = 7;
pub const CAPPED_DY: u8 = 7;
pub const CAPPED_CROSSINGS: u8 = 5;
