//! Generated by vectors.py from model.py: do not edit by hand. Shared vectors of the flood:
//! `(terrain, start, targets, limit, layers, distances, reached)`, distances one byte per
//! target (as `flood::distance_of`), reached the union of the layers.

use crate::boards::{CAPPED_GOBLINS, CAPPED_TERRAIN, DEEP_EVEN_TERRAIN, DEEP_GOBLINS, DEEP_TERRAIN};

pub fn vectors() -> Array<(felt252, u8, Span<u8>, u8, u32, felt252, felt252)> {
    array![
        (CAPPED_TERRAIN, 112, array![].span(), 15, 1, 0x0, 0x10000000000000000000000000000),
        (CAPPED_TERRAIN, 112, array![].span(), 255, 1, 0x0, 0x10000000000000000000000000000),
        (DEEP_EVEN_TERRAIN, 127, array![].span(), 15, 1, 0x0, 0x80000000000000000000000000000000),
        (DEEP_EVEN_TERRAIN, 127, array![].span(), 255, 1, 0x0, 0x80000000000000000000000000000000),
        (
            CAPPED_TERRAIN,
            112,
            array![0].span(),
            15,
            16,
            0x0,
            0xfff9fff2ffe6ffcbff97ff2ffe6ffcbff83ff0f860f7c01f80ff0000,
        ),
        (
            CAPPED_TERRAIN,
            112,
            array![0].span(),
            255,
            22,
            0x0,
            0xfff9fff2ffe6ffcbff97ff2ffe6ffcbff9bff2f866f7cc1f9fff0000,
        ),
        (
            DEEP_EVEN_TERRAIN,
            127,
            array![0].span(),
            15,
            16,
            0x0,
            0x30005000a000a0008003000a0008001400180000,
        ),
        (
            DEEP_EVEN_TERRAIN,
            127,
            array![0].span(),
            255,
            93,
            0x0,
            0xdef95312d1a422cbb414572ea262acb4b15b428ae5e848568fdb0000,
        ),
        (
            CAPPED_TERRAIN,
            112,
            CAPPED_GOBLINS.span(),
            15,
            16,
            0x7050203040f030d,
            0xfff9bff2efe6ffcbff97ff2f8e4ffc3ff83ff0f060f7c01f801f0000,
        ),
        (
            CAPPED_TERRAIN,
            112,
            CAPPED_GOBLINS.span(),
            255,
            16,
            0x7050203040f030d,
            0xfff9bff2efe6ffcbff97ff2f8e4ffc3ff83ff0f060f7c01f801f0000,
        ),
        (
            DEEP_TERRAIN,
            112,
            DEEP_GOBLINS.span(),
            15,
            16,
            0x0,
            0x1c002c0048019000a001c00c0000000000000000,
        ),
        (
            DEEP_TERRAIN,
            112,
            DEEP_GOBLINS.span(),
            255,
            83,
            0x5200000000,
            0xee392b53576150cd5c85ad304a4d94a8a955d2bc65834a028c070000,
        ),
    ]
}
