#!/usr/bin/env python3
"""Generate src/tables.cairo: the constants of the window board and the damage table.

    python3 spikes/SPK-2/gen_tables.py > spikes/SPK-2/src/tables.cairo
then `scarb fmt` from spikes/SPK-2 (CI checks the format), and copy the file to native/src/.
"""

P = 2**251 + 17 * 2**192 + 1
W, H = 15, 16


def inv(k):
    return pow(2**k, P - 2, P)


def felt(v):
    return hex(v % P)


even = sum(((2**W - 1) << (W * y)) for y in range(0, H, 2))
interior = sum(((2 ** (W - 2) - 1) << (W * y + 1)) for y in range(1, H - 1))
inv2 = inv(1)
around_even = (inv2 + 2 + 2 ** (W - 1) + 2**W + inv(W + 1) + inv(W)) % P
around_odd = (inv2 + 2 + 2**W + 2 ** (W + 1) + inv(W) + inv(W - 1)) % P

out = []
out.append("//! Generated by gen_tables.py: do not edit by hand.")
out.append("")
out.append(f"/// Window width and height (D-120).")
out.append(f"pub const WIDTH: u8 = {W};")
out.append(f"pub const HEIGHT: u8 = {H};")
out.append(f"/// Bits of the even rows of the 15 x 16 board.")
out.append(f"pub const EVEN_LOW: u128 = {hex(even % 2**128)};")
out.append(f"pub const EVEN_HIGH: u128 = {hex(even >> 128)};")
out.append(f"/// Bits of the interior (the ring is wall).")
out.append(f"pub const INTERIOR: felt252 = {hex(interior)};")
out.append(f"/// 1/2 in the field.")
out.append(f"pub const INV_2: felt252 = {felt(inv2)};")
out.append(f"/// 2^(W-1): up shift of the even rows.")
out.append(f"pub const UP: felt252 = {hex(2 ** (W - 1))};")
out.append(f"/// 2^-(W+1): down shift of the even rows.")
out.append(f"pub const DOWN: felt252 = {felt(inv(W + 1))};")
out.append(f"/// Field sum of the 6 neighbour offsets of an even-row tile.")
out.append(f"pub const AROUND_EVEN: felt252 = {felt(around_even)};")
out.append(f"/// Field sum of the 6 neighbour offsets of an odd-row tile.")
out.append(f"pub const AROUND_ODD: felt252 = {felt(around_odd)};")
out.append("")
out.append("/// 2^i, i < 252.")
out.append("pub const POW: [felt252; 252] = [")
for i in range(252):
    out.append(f"    {hex(2**i)},")
out.append("];")
out.append("")
# design/04: damage = base x 2^((strength - armor) / 40), x in [-160, 80], clamped.
out.append("/// Damage factor 2^(x/40) in 16.16 fixed point, index x + 160, x in [-160, 80] (design/04).")
out.append("pub const DAMAGE_OFFSET: u16 = 160;")
out.append("pub const DAMAGE_MAX_INDEX: u16 = 240;")
out.append("pub const DAMAGE: [u32; 241] = [")
for x in range(-160, 81):
    out.append(f"    {round(2 ** (x / 40) * 65536)},")
out.append("];")
out.append("")
out.append("/// Number of set bits of a byte.")
out.append("pub const POPCOUNT: [u8; 256] = [")
for i in range(0, 256, 16):
    out.append("    " + ", ".join(str(bin(v).count("1")) for v in range(i, i + 16)) + ",")
out.append("];")
print("\n".join(out))
