//! The words of a revealed chunk: `Terrain` and `Features` (layouts: `models::index`, ENG-01
//! §3.2), stored by `Instances` under `(slot, chunk)` and generated by the reveal (ENG-05,
//! `types::reveal`), or copied from an authored zone's record (D-214, ENG-09). Here, not in the ephemeral package, so that the reveal, the tick and the views
//! read them without a dependency on `Instances` (ENG-05 Open question 4); `Instances`' `Chunk`
//! storage struct imports them, its layout and addresses unchanged (`layout_tests`).
//!
//! A pack's goblins stand on tiles named by their index in `OFFSETS`, the 19 tiles within 2 of the
//! pack's tile (`PackPlacement.offsets`, 5 bits a goblin): the order is by row offset `dr`, then by
//! `dq`, in axial coordinates (`q = x − ⌊y/2⌋`, `r = y`, global), so that it does not depend
//! on the row's parity; index 9 is the pack's own tile. `PackPlacementTrait::member` turns an index
//! into a tile of the chunk.

use crate::packing::{
    LIVE, P16, P24, P32, P36, P64, P8, P96, TWO_POW_128, byte_at, field, fits, join, low_field,
    split, u16_at,
};
pub use super::index::{Features, Object, PackPlacement, Terrain};

/// 2^97: the part of the walls above bit 128, in the high limb.
const P97: u128 = 0x2000000000000000000000000;
/// 2^225, where the edges start.
const P225: felt252 = 0x200000000000000000000000000000000000000000000000000000000;
/// 2^61, the pack's `alert`.
const P61: u128 = 0x2000000000000000;

/// Object kinds (design/18 *Features*; ENG-01 §3.2).
pub mod object {
    pub const NONE: u8 = 0;
    pub const CHEST: u8 = 1;
    pub const VEIN: u8 = 2;
    pub const NODE: u8 = 3;
    /// A terrain trap (ruins and caves); its `param` is a `SKILL` (design/19 §5.11, CBT-05b).
    pub const TRAP: u8 = 4;
    pub const COLLECTOR: u8 = 5;
    pub const LANDMARK: u8 = 6;
    pub const LEVER: u8 = 7;
    /// A dungeon floor's exit, placed by quota (ADR-0006: "the exit is a quota"); its `param` is
    /// the floor gate (ENG-05).
    pub const EXIT: u8 = 8;
    /// A trap set by an actor (design/19 §5.11, CBT-05b).
    pub const PLACED_TRAP: u8 = 9;
}

/// A pack's shared state while none of its goblins has a record.
pub mod alert {
    pub const ASLEEP: u8 = 0;
    pub const WATCH: u8 = 1;
    pub const ALERTED: u8 = 2;
}

/// The index of the pack's own tile in `OFFSETS`.
pub const CENTRE: u8 = 9;
/// Tiles within 2 of a tile.
pub const NEAR: u8 = 19;

pub mod errors {
    pub const WALLS: felt252 = 'packing: walls above bit 224';
    pub const EDGES: felt252 = 'packing: edges above 4 bits';
    pub const COUNT: felt252 = 'packing: pack count above 15';
    pub const OFFSETS: felt252 = 'packing: offsets above 25 bits';
    pub const ALERT: felt252 = 'packing: pack alert above 7';
    pub const KIND: felt252 = 'packing: object kind above 15';
    pub const STATE: felt252 = 'packing: object state above 15';
}

pub impl TerrainStorePacking of starknet::storage_access::StorePacking<Terrain, felt252> {
    fn pack(value: Terrain) -> felt252 {
        let walls: u256 = value.walls.into();
        assert(walls.high < P97, errors::WALLS);
        fits(value.edges.into(), 0x10, errors::EDGES);
        value.walls + value.edges.into() * P225 + LIVE
    }
    fn unpack(value: felt252) -> Terrain {
        let (low, high) = split(value);
        let (edges, walls_high) = DivRem::div_rem(high, P97.try_into().unwrap());
        Terrain {
            walls: low.into() + walls_high.into() * TWO_POW_128,
            edges: low_field(edges, P8.try_into().unwrap()).try_into().unwrap(),
        }
    }
}

/// A pack's 64 bits in the low limb of `Features`.
#[generate_trait]
pub impl PackPlacementImpl of PackPlacementTrait {
    #[inline(never)]
    fn bits(self: @PackPlacement) -> u128 {
        fits((*self.count).into(), 0x10, errors::COUNT);
        fits((*self.offsets).into(), 0x2000000, errors::OFFSETS);
        fits((*self.alert).into(), 0x8, errors::ALERT);
        (*self.alert).into() * P61
            + (*self.tile).into()
            + (*self.template).into() * P8
            + (*self.level).into() * P24
            + (*self.count).into() * P32
            + (*self.offsets).into() * P36
    }

    #[inline(never)]
    fn from_bits(bits: u128) -> PackPlacement {
        PackPlacement {
            tile: low_field(bits, P8.try_into().unwrap()).try_into().unwrap(),
            template: u16_at(bits, P8),
            level: byte_at(bits, P24),
            count: field(bits, P32, 0x10).try_into().unwrap(),
            offsets: field(bits, P36, 0x2000000).try_into().unwrap(),
            alert: field(bits, P61, 0x8).try_into().unwrap(),
        }
    }

    /// The tile of the chunk at index `k` of `OFFSETS` from `tile` (`15 row + column`), `odd`
    /// when the tile's global row is odd (`row + cy` odd); `None` outside the chunk.
    fn member(tile: u8, k: u8, odd: bool) -> Option<u8> {
        let (row, column) = DivRem::div_rem(tile, 15);
        // `dr + 2` and `dq + 2` by `k`'s row of the order (3, 4, 5, 4, 3 offsets), computed
        // rather than read from tables (a constant table is copied at each read in Sierra).
        let (dr, dq) = if k < 3 {
            (0, k + 2)
        } else if k < 7 {
            (1, k - 2)
        } else if k < 12 {
            (2, k - 7)
        } else if k < 16 {
            (3, k - 12)
        } else {
            (4, k - 16)
        };
        // `⌊(y + dr) / 2⌋ − ⌊y / 2⌋ + 1` for the row's parity.
        let half = if odd {
            (dr + 1) / 2
        } else {
            dr / 2
        };
        // `column + dq + half − 1` and `row + dr`, shifted by 3 and 2 so that no step is
        // negative.
        let x = column + dq + half;
        let y = row + dr;
        if x < 3 || x > 17 || y < 2 || y > 16 {
            return Option::None;
        }
        Option::Some((y - 2) * 15 + x - 3)
    }
}

/// An object's 32 bits in the high limb of `Features`.
#[generate_trait]
pub impl ObjectImpl of ObjectTrait {
    #[inline(never)]
    fn bits(self: @Object) -> u128 {
        fits((*self.kind).into(), 0x10, errors::KIND);
        fits((*self.state).into(), 0x10, errors::STATE);
        (*self.tile).into()
            + (*self.kind).into() * P8
            + (*self.state).into() * 0x1000
            + (*self.param).into() * P16
    }

    #[inline(never)]
    fn from_bits(bits: u128) -> Object {
        Object {
            tile: low_field(bits, P8.try_into().unwrap()).try_into().unwrap(),
            kind: field(bits, P8, 0x10).try_into().unwrap(),
            state: field(bits, 0x1000, 0x10).try_into().unwrap(),
            param: u16_at(bits, P16),
        }
    }
}

#[generate_trait]
pub impl FeaturesImpl of FeaturesTrait {
    /// No pack, no object, nothing touched.
    fn empty() -> Features {
        Features { packs: [Default::default(); 2], objects: [Default::default(); 3], touched: 0 }
    }
}

pub impl FeaturesStorePacking of starknet::storage_access::StorePacking<Features, felt252> {
    fn pack(value: Features) -> felt252 {
        let [p0, p1] = value.packs;
        let [o0, o1, o2] = value.objects;
        join(
            p0.bits() + p1.bits() * P64,
            o0.bits() + o1.bits() * P32 + o2.bits() * P64 + value.touched.into() * P96,
        )
    }
    fn unpack(value: felt252) -> Features {
        let (low, high) = split(value);
        let s32: NonZero<u128> = P32.try_into().unwrap();
        let (p1, p0) = DivRem::div_rem(low, P64.try_into().unwrap());
        let (rest, o0) = DivRem::div_rem(high, s32);
        let (rest, o1) = DivRem::div_rem(rest, s32);
        let (touched, o2) = DivRem::div_rem(rest, s32);
        Features {
            packs: [PackPlacementTrait::from_bits(p0), PackPlacementTrait::from_bits(p1)],
            objects: [
                ObjectTrait::from_bits(o0), ObjectTrait::from_bits(o1), ObjectTrait::from_bits(o2),
            ],
            touched: touched.try_into().unwrap(),
        }
    }
}

#[cfg(test)]
mod tests {
    use hexx::board::bits::Bits;
    use starknet::storage_access::StorePacking;
    use crate::packing::LIVE;
    use crate::types::window::WindowTrait;
    use super::{
        CENTRE, Features, FeaturesStorePacking, FeaturesTrait, NEAR, Object, PackPlacement,
        PackPlacementTrait, Terrain, TerrainStorePacking,
    };

    // The 19 tiles within 2 against ENG-02's hex distance (`WindowTrait::distance`, its own
    // oracle): distinct, within 2, by row. A chunk's rows have the window's parity when its local
    // row 0 is even, and are a row up (`+ 15`) when it is odd; `member` takes the global parity of
    // the tile's row.
    fn check_members(tile: u8, chunk_odd: bool) {
        let shift: u8 = if chunk_odd {
            15
        } else {
            0
        };
        let (row, _) = DivRem::div_rem(tile, 15);
        let odd = (row % 2 == 1) != chunk_odd;
        let mut seen: felt252 = 0;
        let mut last_row: u8 = 0;
        let mut k: u8 = 0;
        while k != NEAR {
            let member = PackPlacementTrait::member(tile, k, odd).unwrap();
            assert(WindowTrait::distance(tile + shift, member + shift) <= 2, 'within 2');
            let (row, _) = DivRem::div_rem(member, 15);
            assert(row >= last_row, 'by row');
            last_row = row;
            let bit = Bits::pow(member);
            let wide: u256 = seen.into();
            assert(!Bits::get(wide, member), 'distinct');
            seen += bit;
            k += 1;
        }
        assert(PackPlacementTrait::member(tile, CENTRE, odd) == Some(tile), 'centre');
    }

    #[test]
    #[available_gas(l2_gas: 2671692)] // ceil(1.05 × 2544468 measured)
    fn test_member_offsets() {
        check_members(6 * 15 + 7, false);
        check_members(7 * 15 + 7, false);
        check_members(6 * 15 + 7, true);
        check_members(7 * 15 + 7, true);
        // Outside the chunk: off the West column, below row 0, off the East one, above row 14.
        assert(PackPlacementTrait::member(14, 11, false).is_none(), 'west');
        assert(PackPlacementTrait::member(7, 0, false).is_none(), 'south');
        assert(PackPlacementTrait::member(0, 7, false).is_none(), 'east');
        assert(PackPlacementTrait::member(224, 18, true).is_none(), 'north');
    }

    // Every field at its bits (ENG-01 §3.2), and back.
    #[test]
    #[available_gas(l2_gas: 408051)] // ceil(1.05 × 388620 measured)
    fn test_words_round_trip() {
        let terrain = Terrain {
            walls: 0x1ffffffffffffffffffffffffffffffffffffffffffffffffffffffff, edges: 0xb,
        };
        let word = StorePacking::<Terrain, felt252>::pack(terrain);
        assert(
            word == terrain.walls
                + 0xb * 0x200000000000000000000000000000000000000000000000000000000
                + LIVE,
            'terrain bits',
        );
        assert(StorePacking::<Terrain, felt252>::unpack(word) == terrain, 'terrain trip');
        let pack = PackPlacement {
            tile: 0xab, template: 0x1234, level: 0x56, count: 5, offsets: 0x1abcdef, alert: 2,
        };
        assert(
            pack.bits() == 0xab
                + 0x1234 * 0x100
                + 0x56 * 0x1000000
                + 5 * 0x100000000
                + 0x1abcdef * 0x1000000000
                + 2 * 0x2000000000000000,
            'pack bits',
        );
        let object = Object { tile: 0xcd, kind: 8, state: 1, param: 0xbeef };
        let features = Features {
            packs: [pack, Default::default()],
            objects: [Default::default(), object, object],
            touched: 0x3ff,
        };
        let word = StorePacking::<Features, felt252>::pack(features);
        assert(StorePacking::<Features, felt252>::unpack(word) == features, 'features trip');
        let empty = FeaturesTrait::empty();
        assert(StorePacking::<Features, felt252>::pack(empty) == LIVE, 'empty');
    }

    #[test]
    #[should_panic(expected: 'packing: walls above bit 224')]
    #[available_gas(l2_gas: 10385)] // ceil(1.05 × 9890 measured)
    fn test_walls_refused_above_224() {
        StorePacking::<
            Terrain, felt252,
        >::pack(
            Terrain {
                walls: 0x2000000000000000000000000000000000000000000000000000000000, edges: 0,
            },
        );
    }
}
