//! One hit (design/19 §5.5 steps 1–4, §5.6; CBT-03a, D-170): from the hit's inputs to its
//! outcome, stopped (missed, blocked, evaded) or landed with its damage. Pure: no storage, no draw,
//! no world.
//! CBT-05's executor gathers the inputs from the world and applies the outcome (§5.5 steps 5–9).
//!
//! A value type, not stored on its own: `types/`, not `models/` (docs/CAIRO.md §7).
//!
//! Inputs provided by later lots:
//! - **ENG-02** (line of sight and arcs on `hexx`, wired by CBT-03b): `Hit.arc`, the arc of the
//!   target the source's tile, or at range the tile the line of sight arrives from, lies in; and
//!   `Hit.in_front`, whether the target is on the source's front tile (Blind's miss). The flank is
//!   the rear-side arc (design/04): it is not a separate input.
//! - **CBT-04** (conditions): `HitTarget.knocked_down`; `Hit.weakened` and `Hit.blind` (**P**: no
//!   MVP source, FX-22; the inputs exist, the MVP never sets them).
//!
//! The vector table for the TypeScript mirror (D-140, SPK-4) is printed by `tests::test_vectors`
//! and kept in `contracts/logic/vectors/hit.jsonl`: one line per case, `{"id", "case", "ok"}`, the
//! case `Serde` of `(Hit, HitTarget)` and the outcome `Serde` of `HitOutcome`, each felt in hex (a
//! negative integer is `P − |v|`). Regenerated by
//! `snforge test grimworld_logic::types::hit::tests::test_vectors | grep '^{"id"'`; the test holds
//! a digest of every outcome, so a change to a rule fails it until the table is regenerated.
//!
//! The felts of a vector, in order (a boolean is 0 or 1; an enum is its variant's index):
//!
//! `case`, 28 felts, `Hit` then `HitTarget`:
//! - 0 `class`: 0 `Weapon`, 1 `Spell`, 2 `Item`, 3 `Trap`
//! - 1 `weapon`: `combat::weapon`, 0 none, 2 the axe
//! - 2 `melee`
//! - 3 `arc`: 0 `Front`, 1 `FrontSide`, 2 `RearSide`, 3 `Back`
//! - 4 `in_front`
//! - 5 `strength`
//! - 6 `base`
//! - 7 `percent` (signed)
//! - 8 `percent_above_half` (signed)
//! - 9 `penetration`
//! - 10 `health` (the source's)
//! - 11 `max_health` (the source's)
//! - 12 `weakened`
//! - 13 `blind`
//! - 14 `armor` (signed)
//! - 15 `armor_effects`
//! - 16 `armor_stance` (signed)
//! - 17 `armor_enchanted` (signed)
//! - 18 `in_stance`
//! - 19 `enchanted`
//! - 20 `armor_vs`
//! - 21 `block`
//! - 22 `evade`
//! - 23 `knocked_down`
//! - 24 `asleep`
//! - 25 `halve`
//! - 26 `health` (the target's)
//! - 27 `max_health` (the target's)
//!
//! `ok`, `HitOutcome`: 1 felt for a stopped hit, 4 for a landed one:
//! - 0 the variant: 0 `Missed`, 1 `Blocked`, 2 `Evaded`, 3 `Landed`
//! - 1 `damage` (`Landed` only)
//! - 2 `critical` (`Landed` only)
//! - 3 `halved` (`Landed` only)

use crate::helpers::exp2::{Exp2, SHIFT};
use crate::snapshot::STRENGTH_PER_RANK;
use super::combat::{Arc, HitClass, weapon};

/// A critical strike: +40 % (design/04).
pub const CRITICAL_PERCENT: i32 = 40;
/// The axe, from the rear-side and back arcs: +25 % (design/04).
pub const AXE_PERCENT: i32 = 25;
/// Weakness on the source: −33 % to its weapon hits (design/19 §3.2, **P**).
pub const WEAKNESS_PERCENT: i32 = -33;
/// The sum of the percents is never below −100 (D-140).
pub const MIN_PERCENT: i32 = -100;
/// Penetration is capped at 100 % (FX-9).
pub const PENETRATION_CAP: u32 = 100;
/// The damage of one hit is clamped to [0, 65,535] (D-140).
pub const MAX_DAMAGE: u64 = 65535;
/// Strength of a spell and a trap: 3 × level (design/04, FX-28).
pub const STRENGTH_PER_LEVEL: u16 = 3;
/// A weapon's damage below its requirement is divided by 3 (design/15).
pub const REQUIREMENT_DIVISOR: u32 = 3;
/// The largest base of a hit: a weapon's damage ≤ 255 and one `ATTACK_BONUS` ≤ 32,767
/// (design/20 §1.6, case B, DS-18, DS-20); a `DAMAGE` entry is ≤ 32,767. `base × table(80)` <
/// 2^34: a `u64`.
pub const MAX_BASE: u32 = 33022;
/// A `BLOCK`'s charges, 1…63 (design/19 §3.4); 0 is none held.
pub const MAX_BLOCK: u8 = 63;

pub mod errors {
    pub const BASE: felt252 = 'hit: base above its bound';
    pub const HEALTH: felt252 = 'hit: health above max';
    pub const BLOCK: felt252 = 'hit: block charges';
}

/// One hit and its source (design/19 §5.5): the class, the arc, the source's strength and base,
/// the percents and penetrations that apply, the source's state.
#[derive(Copy, Drop, Serde, PartialEq, Debug)]
pub struct Hit {
    /// What applies to it (§5.4).
    pub class: HitClass,
    /// The source's weapon class (`combat::weapon`, 0 none): the axe's +25 %. `WEAPON` only.
    pub weapon: u8,
    /// The weapon's range is 1: evasion takes melee hits only (§3.4). `WEAPON` only.
    pub melee: bool,
    /// The arc of the target it arrives from (ENG-02). `WEAPON` only (FX-27).
    pub arc: Arc,
    /// The target is on the source's front tile (ENG-02): Blind's miss. `WEAPON` only.
    pub in_front: bool,
    /// The source's strength by class: `HitTrait::weapon_strength`, `level_strength`, or a bomb's
    /// recipe (§5.4, FX-28).
    pub strength: u16,
    /// The base damage: `HitTrait::weapon_base` for a weapon hit, the `DAMAGE` entry's value for
    /// another class; ≤ `MAX_BASE`.
    pub base: u32,
    /// The source's `DAMAGE_PERCENT` sums for this class (§7.2: plain weapon, attack skill or
    /// spell), unguarded and `ABOVE_HALF`. `WEAPON` and `SPELL` only (§5.4).
    pub percent: i16,
    pub percent_above_half: i16,
    /// The penetrations that apply to this class, summed: the `PENETRATION` passive of the class,
    /// the source's `PENETRATION` effects of its scope, the carrier's `HIT_PENETRATION`; capped at
    /// 100 here. `WEAPON` and `SPELL` only (§5.4).
    pub penetration: u16,
    /// The source's health and max health, for the `ABOVE_HALF` guard at the damage step (§2.4).
    pub health: u16,
    pub max_health: u16,
    /// The source holds Weakness (CBT-04; **P**). `WEAPON` only.
    pub weakened: bool,
    /// The source holds Blind (CBT-04; **P**). `WEAPON` only.
    pub blind: bool,
}

/// The target of a hit: its armor terms and its state (design/19 §5.5 step 3, §5.6).
#[derive(Copy, Drop, Serde, PartialEq, Debug)]
pub struct HitTarget {
    /// The unguarded armor, signed: the snapshot's `i16` (F-20), or the caste's.
    pub armor: i16,
    /// Its `ARMOR` effects, summed (each 0…255).
    pub armor_effects: u16,
    /// Its guarded `ARMOR` sums, signed (F-20), and whether their guards hold (subject the target).
    pub armor_stance: i8,
    pub armor_enchanted: i8,
    pub in_stance: bool,
    pub enchanted: bool,
    /// Its `ARMOR_VS` of the hit's damage type (≤ 63, FX-23).
    pub armor_vs: u8,
    /// The charges of the `BLOCK` it holds; 0 none.
    pub block: u8,
    /// It holds `EVADE` (melee).
    pub evade: bool,
    /// It is knocked down (CBT-04): critical from any arc, neither blocks nor evades (FX-7).
    pub knocked_down: bool,
    /// It is asleep: critical from any arc, and this first hit can be neither blocked (design/04)
    /// nor evaded (D-179).
    pub asleep: bool,
    /// It holds `HALVE_FIRST_HEAVY_HIT`, not yet spent (FX-19).
    pub halve: bool,
    /// Its health and max health before the hit (FX-19).
    pub health: u16,
    pub max_health: u16,
}

/// A landed hit (FX-10: whatever its damage, 0 included).
#[derive(Copy, Drop, Serde, PartialEq, Debug)]
pub struct Landed {
    /// The damage, in [0, 65,535], after FX-19's halving.
    pub damage: u16,
    /// It was a critical strike.
    pub critical: bool,
    /// FX-19's halving triggered: the executor marks it spent.
    pub halved: bool,
}

/// What a hit does (§5.5 step 2, §5.6). A stopped hit is not a hit: nothing of it or of its
/// carrier applies to the target.
#[derive(Copy, Drop, Serde, PartialEq, Debug)]
pub enum HitOutcome {
    /// Blind's miss (**P**).
    Missed,
    /// Blocked: the executor spends one of the target's `BLOCK` charges.
    Blocked,
    /// Evaded.
    Evaded,
    Landed: Landed,
}

#[generate_trait]
pub impl HitImpl of HitTrait {
    /// §5.5 steps 1–4 and §5.6: the outcome of the hit on the target.
    fn resolve(self: @Hit, target: @HitTarget) -> HitOutcome {
        HitAssert::assert_valid(self, target);
        let weapon_hit = *self.class == HitClass::Weapon;
        if weapon_hit {
            let stop = self.stop(target);
            if stop.is_some() {
                return stop.unwrap();
            }
        }
        let critical = weapon_hit && self.is_critical(target);
        let damage = self.damage(self.armor(target), self.percent(target, critical));
        let (damage, halved) = if weapon_hit {
            target.halve(damage)
        } else {
            (damage, false)
        };
        HitOutcome::Landed(Landed { damage: damage.try_into().unwrap(), critical, halved })
    }

    /// Step 2 of a weapon hit (§5.6), in §5.5's order: a miss, a block, an evasion; `None` if it
    /// goes on.
    #[inline(always)]
    fn stop(self: @Hit, target: @HitTarget) -> Option<HitOutcome> {
        if *self.blind && !*self.in_front {
            return Option::Some(HitOutcome::Missed);
        }
        let open = !*target.knocked_down;
        let front = *self.arc == Arc::Front || *self.arc == Arc::FrontSide;
        if *target.block > 0 && front && open && !*target.asleep {
            return Option::Some(HitOutcome::Blocked);
        }
        // D-179: a sleeping target neither blocks nor evades its first hit (the executor clears
        // `asleep` when it notices, §5.5 step 9).
        if *target.evade && *self.melee && open && !*target.asleep {
            return Option::Some(HitOutcome::Evaded);
        }
        Option::None
    }

    /// A weapon hit is critical from the back, or on a knocked-down or sleeping target from any arc
    /// (design/04).
    #[inline(always)]
    fn is_critical(self: @Hit, target: @HitTarget) -> bool {
        *self.arc == Arc::Back || *target.knocked_down || *target.asleep
    }

    /// Step 3: the final armor, never below 0. `a` signed, floored at 0 (D-140, F-20), then
    /// `a⁺ − ⌊a⁺ × p / 100⌋` with `p` the penetration capped at 100 (FX-9), 0 for a bomb
    /// or a trap.
    #[inline(always)]
    fn armor(self: @Hit, target: @HitTarget) -> u32 {
        let mut a: i32 = (*target.armor).into()
            + (*target.armor_effects).into()
            + (*target.armor_vs).into();
        if *target.in_stance {
            a += (*target.armor_stance).into();
        }
        if *target.enchanted {
            a += (*target.armor_enchanted).into();
        }
        if a <= 0 {
            return 0;
        }
        let a: u32 = a.try_into().unwrap();
        let p: u32 = if self.reads_passives() {
            let p: u32 = (*self.penetration).into();
            if p > PENETRATION_CAP {
                PENETRATION_CAP
            } else {
                p
            }
        } else {
            0
        };
        a - a * p / 100
    }

    /// The sum of the percents that apply (§5.4), floored at −100 (D-140): the source's
    /// `DAMAGE_PERCENT` (the `ABOVE_HALF` sum if its guard holds) for a weapon hit or a spell; the
    /// critical, the axe's and Weakness's for a weapon hit.
    #[inline(always)]
    fn percent(self: @Hit, target: @HitTarget, critical: bool) -> i32 {
        let mut sum: i32 = 0;
        if self.reads_passives() {
            sum += (*self.percent).into();
            let health: u32 = (*self.health).into();
            if health * 2 > (*self.max_health).into() {
                sum += (*self.percent_above_half).into();
            }
        }
        if *self.class == HitClass::Weapon {
            if critical {
                sum += CRITICAL_PERCENT;
            }
            if *self.weapon == weapon::AXE
                && (*self.arc == Arc::RearSide || *self.arc == Arc::Back) {
                sum += AXE_PERCENT;
            }
            if *self.weakened {
                sum += WEAKNESS_PERCENT;
            }
        }
        if sum < MIN_PERCENT {
            MIN_PERCENT
        } else {
            sum
        }
    }

    /// Step 4 before FX-19: `x = strength − armor` clamped to [−160, +80] by the table,
    /// `⌊base × table(x) / 2^16⌋`, then `⌊· × (100 + percent) / 100⌋`, clamped to [0,
    /// 65,535].
    /// `percent` ≥ −100, so nothing is negative and 0 is the lower bound by itself.
    ///
    /// **Precondition**: `percent` ≥ −100 (else `100 + percent` does not fit a `u64`), and
    /// `armor` ≤ `i32::MAX` (else it does not fit the exponent's `i32`); either breach panics.
    /// `resolve` always meets both: `percent` returns a sum floored at −100, and `armor` is below
    /// 10^5 for every legal input. A caller other than `resolve` (a test, CBT-05) must meet them
    /// too, or call `resolve`.
    #[inline(always)]
    fn damage(self: @Hit, armor: u32, percent: i32) -> u64 {
        let x: i32 = (*self.strength).into() - armor.try_into().unwrap();
        let factor: u64 = Exp2::at(x).into();
        let base: u64 = (*self.base).into();
        let scaled = base * factor / SHIFT.into();
        let multiplier: u64 = (100 + percent).try_into().unwrap();
        let damage = scaled * multiplier / 100;
        if damage > MAX_DAMAGE {
            MAX_DAMAGE
        } else {
            damage
        }
    }

    /// The class reads the source's `DAMAGE_PERCENT` and the penetrations (§5.4: weapon and spell,
    /// by scope; not a bomb, not a trap).
    #[inline(always)]
    fn reads_passives(self: @Hit) -> bool {
        *self.class == HitClass::Weapon || *self.class == HitClass::Spell
    }

    /// A weapon hit's strength: `5 × rank` of the weapon's attribute, capped (design/04, DS-9; the
    /// cap is the level's, `Loadout.strength_cap`).
    fn weapon_strength(rank: u8, cap: u8) -> u16 {
        let strength = STRENGTH_PER_RANK * rank.into();
        let cap: u16 = cap.into();
        if strength > cap {
            cap
        } else {
            strength
        }
    }

    /// A spell's or a trap's strength: `3 × level` (design/04, FX-28).
    fn level_strength(level: u8) -> u16 {
        STRENGTH_PER_LEVEL * level.into()
    }

    /// A weapon hit's base: the weapon's damage, divided by 3 below its requirement (design/15),
    /// plus an attack skill's `ATTACK_BONUS` (§3.1; 0 for a plain attack).
    fn weapon_base(damage: u8, requirement_met: bool, bonus: u16) -> u32 {
        let damage: u32 = damage.into();
        let damage = if requirement_met {
            damage
        } else {
            damage / REQUIREMENT_DIVISOR
        };
        damage + bonus.into()
    }
}

#[generate_trait]
pub impl HitTargetImpl of HitTargetTrait {
    /// FX-19, on a weapon hit's final damage: if the target holds the halving unspent, and the hit
    /// would bring it from at least 50 % to below 50 % (`2h ≥ max ∧ 2(h ⊖ d) < max`), the
    /// damage is halved, truncated. Returns the damage and whether it triggered.
    #[inline(always)]
    fn halve(self: @HitTarget, damage: u64) -> (u64, bool) {
        if !*self.halve {
            return (damage, false);
        }
        let health: u64 = (*self.health).into();
        let max: u64 = (*self.max_health).into();
        let after = if damage > health {
            0
        } else {
            health - damage
        };
        if health * 2 >= max && after * 2 < max {
            (damage / 2, true)
        } else {
            (damage, false)
        }
    }
}

#[generate_trait]
pub impl HitAssert of HitAssertTrait {
    /// What an input may not be: a base above `MAX_BASE` (the content and the snapshot bound it), a
    /// health above its max, a `BLOCK` above 63 charges. A breach is a bug, not a play (D-140).
    #[inline(always)]
    fn assert_valid(hit: @Hit, target: @HitTarget) {
        assert(*hit.base <= MAX_BASE, errors::BASE);
        assert(*hit.health <= *hit.max_health, errors::HEALTH);
        assert(*target.health <= *target.max_health, errors::HEALTH);
        assert(*target.block <= MAX_BLOCK, errors::BLOCK);
    }
}

#[cfg(test)]
mod tests {
    use super::{
        Arc, Hit, HitAssert, HitClass, HitOutcome, HitTarget, HitTargetTrait, HitTrait, Landed,
        MAX_BASE, weapon,
    };

    /// A plain sword hit from the front, strength equal to armor (x = 0, `table(0) = 2^16`), at
    /// base 100, no modifier.
    fn sword() -> Hit {
        Hit {
            class: HitClass::Weapon,
            weapon: weapon::SWORD,
            melee: true,
            arc: Arc::Front,
            in_front: true,
            strength: 40,
            base: 100,
            percent: 0,
            percent_above_half: 0,
            penetration: 0,
            health: 0,
            max_health: 0,
            weakened: false,
            blind: false,
        }
    }

    /// A target of armor 40 in all, at full health, holding nothing.
    fn goblin() -> HitTarget {
        HitTarget {
            armor: 40,
            armor_effects: 0,
            armor_stance: 0,
            armor_enchanted: 0,
            in_stance: false,
            enchanted: false,
            armor_vs: 0,
            block: 0,
            evade: false,
            knocked_down: false,
            asleep: false,
            halve: false,
            health: 100,
            max_health: 100,
        }
    }

    fn landed(outcome: HitOutcome) -> Landed {
        match outcome {
            HitOutcome::Landed(landed) => landed,
            _ => core::panic_with_felt252('not landed'),
        }
    }

    fn damage(hit: Hit, target: HitTarget) -> u16 {
        landed(hit.resolve(@target)).damage
    }

    // ---- §5.4: strength and base by class ----------------------------------------------------

    // Weapon: 5 × rank, capped by the level's cap (design/04, DS-9).
    #[test]
    #[available_gas(l2_gas: 6311)] // ceil(1.05 × 6010 measured)
    fn test_strength_weapon() {
        assert(HitTrait::weapon_strength(10, 255) == 50, '5 x 10');
        assert(HitTrait::weapon_strength(10, 40) == 40, 'capped');
        assert(HitTrait::weapon_strength(15, 75) == 75, '5 x 15');
        assert(HitTrait::weapon_strength(0, 75) == 0, 'rank 0');
    }

    // Spell and trap: 3 × level (design/04, FX-28); a bomb's is its recipe's, taken as is.
    #[test]
    #[available_gas(l2_gas: 15005)] // ceil(1.05 × 14290 measured)
    fn test_strength_level() {
        assert(HitTrait::level_strength(20) == 60, '3 x 20');
        assert(HitTrait::level_strength(255) == 765, '3 x 255');
        let bomb = Hit { class: HitClass::Item, strength: 200, base: 50, ..sword() };
        // x = 200 − 40 = 160, clamped to 80: × 4.
        assert(damage(bomb, goblin()) == 200, 'recipe strength');
    }

    // Base: the weapon's damage after requirement, + `ATTACK_BONUS` (§3.1, design/15).
    #[test]
    #[available_gas(l2_gas: 6311)] // ceil(1.05 × 6010 measured)
    fn test_weapon_base() {
        assert(HitTrait::weapon_base(18, true, 0) == 18, 'met');
        assert(HitTrait::weapon_base(18, false, 0) == 6, 'below requirement: / 3');
        assert(HitTrait::weapon_base(17, false, 0) == 5, 'truncated');
        assert(HitTrait::weapon_base(18, true, 12) == 30, 'attack bonus');
        assert(HitTrait::weapon_base(18, false, 12) == 18, 'bonus after requirement');
        assert(HitTrait::weapon_base(255, true, 32767) == MAX_BASE, 'the bound');
    }

    // ---- §5.4: arcs, critical, axe, weakness --------------------------------------------------

    #[test]
    #[available_gas(l2_gas: 41927)] // ceil(1.05 × 39930 measured)
    fn test_arcs_weapon() {
        assert(damage(sword(), goblin()) == 100, 'front');
        assert(damage(Hit { arc: Arc::FrontSide, ..sword() }, goblin()) == 100, 'front-side');
        assert(damage(Hit { arc: Arc::RearSide, ..sword() }, goblin()) == 100, 'flank: no bonus');
        let back = landed(Hit { arc: Arc::Back, ..sword() }.resolve(@goblin()));
        assert(back.damage == 140 && back.critical, 'back: critical +40');
    }

    #[test]
    #[available_gas(l2_gas: 50411)] // ceil(1.05 × 48010 measured)
    fn test_axe() {
        let axe = Hit { weapon: weapon::AXE, ..sword() };
        assert(damage(axe, goblin()) == 100, 'front: none');
        assert(damage(Hit { arc: Arc::FrontSide, ..axe }, goblin()) == 100, 'front-side: none');
        assert(damage(Hit { arc: Arc::RearSide, ..axe }, goblin()) == 125, 'rear-side +25');
        assert(damage(Hit { arc: Arc::Back, ..axe }, goblin()) == 165, 'back +40 +25');
        let down = HitTarget { knocked_down: true, ..goblin() };
        assert(damage(axe, down) == 140, 'knocked down: critical only');
    }

    // Knocked down or asleep: critical from any arc (design/04, §3.2), once.
    #[test]
    #[available_gas(l2_gas: 33128)] // ceil(1.05 × 31550 measured)
    fn test_critical_any_arc() {
        let down = HitTarget { knocked_down: true, ..goblin() };
        let asleep = HitTarget { asleep: true, ..goblin() };
        let result = landed(sword().resolve(@down));
        assert(result.damage == 140 && result.critical, 'knocked down, front');
        assert(damage(sword(), asleep) == 140, 'asleep, front');
        assert(damage(Hit { arc: Arc::Back, ..sword() }, down) == 140, 'one critical');
    }

    // Arcs, critical, block, evasion, weakness are weapon-only (§5.4, FX-27).
    #[test]
    #[available_gas(l2_gas: 77144)] // ceil(1.05 × 73470 measured)
    fn test_other_classes_take_no_arc() {
        let target = HitTarget { knocked_down: true, block: 3, evade: true, ..goblin() };
        let mut classes = array![HitClass::Spell, HitClass::Item, HitClass::Trap];
        while let Option::Some(class) = classes.pop_front() {
            let hit = Hit {
                class,
                arc: Arc::Back,
                weapon: weapon::AXE,
                weakened: true,
                blind: true,
                in_front: false,
                ..sword(),
            };
            let result = landed(hit.resolve(@target));
            assert(result.damage == 100 && !result.critical, 'no arc, no stop');
        }
    }

    // Weakness −33 % (P), summed with the critical: 107 % (design/04 *Edges*, D-140).
    #[test]
    #[available_gas(l2_gas: 24434)] // ceil(1.05 × 23270 measured)
    fn test_weakness() {
        let weak = Hit { weakened: true, ..sword() };
        assert(damage(weak, goblin()) == 67, '-33');
        assert(damage(Hit { arc: Arc::Back, ..weak }, goblin()) == 107, 'critical and weak');
    }

    // ---- §5.6: miss, block, evasion -----------------------------------------------------------

    #[test]
    #[available_gas(l2_gas: 33128)] // ceil(1.05 × 31550 measured)
    fn test_block_by_arc() {
        let target = HitTarget { block: 2, ..goblin() };
        assert(sword().resolve(@target) == HitOutcome::Blocked, 'front blocked');
        let side = Hit { arc: Arc::FrontSide, ..sword() };
        assert(side.resolve(@target) == HitOutcome::Blocked, 'front-side blocked');
        assert(damage(Hit { arc: Arc::RearSide, ..sword() }, target) == 100, 'flank ignores');
        assert(damage(Hit { arc: Arc::Back, ..sword() }, target) == 140, 'back ignores');
        let none = HitTarget { block: 0, ..goblin() };
        assert(damage(sword(), none) == 100, '0 charges: ended');
        let bow = Hit { melee: false, ..sword() };
        assert(bow.resolve(@target) == HitOutcome::Blocked, 'a ranged hit is blocked');
    }

    #[test]
    #[available_gas(l2_gas: 24434)] // ceil(1.05 × 23270 measured)
    fn test_block_knocked_down_or_asleep() {
        let down = HitTarget { block: 2, knocked_down: true, ..goblin() };
        assert(damage(sword(), down) == 140, 'knocked down: no block');
        let asleep = HitTarget { block: 2, asleep: true, ..goblin() };
        assert(damage(sword(), asleep) == 140, 'asleep: first not blocked');
    }

    // Evasion: melee weapon hits from every arc (FX-11); not a knocked-down target (FX-7).
    #[test]
    // gas: raised, CBT-05a: D-179's case and track CV's three hit cases
    #[available_gas(l2_gas: 81911)] // ceil(1.05 × 78010 measured)
    fn test_evade() {
        let target = HitTarget { evade: true, ..goblin() };
        let mut arcs = array![Arc::Front, Arc::FrontSide, Arc::RearSide, Arc::Back];
        while let Option::Some(arc) = arcs.pop_front() {
            assert(Hit { arc, ..sword() }.resolve(@target) == HitOutcome::Evaded, 'every arc');
        }
        assert(damage(Hit { melee: false, ..sword() }, target) == 100, 'ranged not evaded');
        let down = HitTarget { knocked_down: true, ..target };
        assert(damage(sword(), down) == 140, 'knocked down: no evasion');
        // D-179: a sleeping target neither blocks nor evades its first hit.
        let asleep = HitTarget { asleep: true, ..target };
        assert(damage(sword(), asleep) == 140, 'asleep: no evasion');
        // Block comes before evasion (§5.5 step 2's order): a charge is spent, not an evasion.
        let both = HitTarget { block: 1, ..target };
        assert(sword().resolve(@both) == HitOutcome::Blocked, 'block first');
        assert(Hit { arc: Arc::Back, ..sword() }.resolve(@both) == HitOutcome::Evaded, 'back');
    }

    // Blind (P): a weapon hit misses unless the target is on the source's front tile; before a
    // block, so no charge is spent.
    #[test]
    #[available_gas(l2_gas: 15005)] // ceil(1.05 × 14290 measured)
    fn test_blind_miss() {
        let blind = Hit { blind: true, in_front: false, ..sword() };
        let target = HitTarget { block: 1, ..goblin() };
        assert(blind.resolve(@target) == HitOutcome::Missed, 'missed');
        assert(blind.resolve(@goblin()) == HitOutcome::Missed, 'missed, no block');
        let front = Hit { in_front: true, ..blind };
        assert(front.resolve(@target) == HitOutcome::Blocked, 'on the front tile');
        assert(damage(front, goblin()) == 100, 'lands');
    }

    // ---- §5.5 step 3: armor -------------------------------------------------------------------

    // Every term of `a`, the guards read from the target (§2.4); every class takes armor (§5.4).
    #[test]
    #[available_gas(l2_gas: 108591)] // ceil(1.05 × 103420 measured)
    fn test_armor_terms() {
        let target = HitTarget {
            armor: 10,
            armor_effects: 15,
            armor_stance: 7,
            armor_enchanted: -3,
            in_stance: true,
            enchanted: true,
            armor_vs: 11,
            ..goblin(),
        };
        assert(sword().armor(@target) == 40, 'all terms');
        let out = HitTarget { in_stance: false, enchanted: false, ..target };
        assert(sword().armor(@out) == 36, 'guards false');
        let mut classes = array![HitClass::Weapon, HitClass::Spell, HitClass::Item, HitClass::Trap];
        while let Option::Some(class) = classes.pop_front() {
            assert(damage(Hit { class, ..sword() }, target) == 100, 'armor for every class');
        }
        // +40 armor halves damage (design/04).
        let plus40 = HitTarget { armor: 80, ..goblin() };
        assert(damage(sword(), plus40) == 50, '+40 halves');
    }

    // §6: armor below 0 counts 0 before penetration (D-140, F-20); a negative term counts
    // before the floor.
    #[test]
    #[available_gas(l2_gas: 15005)] // ceil(1.05 × 14290 measured)
    fn test_armor_below_zero() {
        let negative = HitTarget { armor: -500, armor_effects: 20, ..goblin() };
        assert(sword().armor(@negative) == 0, 'floored');
        let pen = Hit { penetration: 50, ..sword() };
        assert(pen.armor(@negative) == 0, 'floored before penetration');
        // −30 + 20 + 50: the negative term counts before the floor.
        let mixed = HitTarget { armor: -30, armor_effects: 20, armor_vs: 50, ..goblin() };
        assert(sword().armor(@mixed) == 40, 'negative counts');
        let stance = HitTarget { armor_stance: -18, in_stance: true, armor: 10, ..goblin() };
        assert(sword().armor(@stance) == 0, 'guarded negative');
        // Strength 40 against armor 0: x = 40, × 2.
        assert(damage(sword(), negative) == 200, 'damage at armor 0');
    }

    // §6: penetration capped at 100 (FX-9); truncated; weapon and spell only (§5.4).
    #[test]
    #[available_gas(l2_gas: 6311)] // ceil(1.05 × 6010 measured)
    fn test_penetration() {
        let target = HitTarget { armor: 41, ..goblin() };
        assert(Hit { penetration: 25, ..sword() }.armor(@target) == 31, '41 - 10');
        assert(Hit { penetration: 100, ..sword() }.armor(@target) == 0, '100 %');
        assert(Hit { penetration: 300, ..sword() }.armor(@target) == 0, 'above 100: 100');
        assert(Hit { penetration: 0xFFFF, ..sword() }.armor(@target) == 0, 'u16 max');
        let spell = Hit { class: HitClass::Spell, penetration: 100, ..sword() };
        assert(spell.armor(@target) == 0, 'spell');
        let bomb = Hit { class: HitClass::Item, penetration: 100, ..sword() };
        assert(bomb.armor(@target) == 41, 'bomb: none');
        let trap = Hit { class: HitClass::Trap, penetration: 100, ..sword() };
        assert(trap.armor(@target) == 41, 'trap: none');
    }

    // ---- §5.5 step 4: damage ------------------------------------------------------------------

    // §6: the exponent at both clamps.
    #[test]
    #[available_gas(l2_gas: 40730)] // ceil(1.05 × 38790 measured)
    fn test_exponent_clamps() {
        let zero = HitTarget { armor: 0, ..goblin() };
        assert(damage(Hit { strength: 80, ..sword() }, zero) == 400, 'x = 80');
        assert(damage(Hit { strength: 765, ..sword() }, zero) == 400, 'x above 80');
        let heavy = HitTarget { armor: 160, ..goblin() };
        assert(damage(Hit { strength: 0, ..sword() }, heavy) == 6, 'x = -160');
        let wall = HitTarget { armor: 32767, armor_effects: 0xFFFF, ..goblin() };
        assert(damage(Hit { strength: 0, ..sword() }, wall) == 6, 'x below -160');
    }

    // The percents summed once, truncated (X-5, D-140); `DAMAGE_PERCENT` by guard; ≥ −100.
    #[test]
    #[available_gas(l2_gas: 59315)] // ceil(1.05 × 56490 measured)
    fn test_percents() {
        let hit = Hit { base: 33, percent: 15, ..sword() };
        // ⌊33 × 115 / 100⌋ = 37 (37.95).
        assert(damage(hit, goblin()) == 37, 'summed, truncated');
        let guarded = Hit { percent_above_half: 15, health: 241, max_health: 480, ..hit };
        assert(damage(guarded, goblin()) == 42, 'above half: +30');
        let half = Hit { health: 240, ..guarded };
        assert(damage(half, goblin()) == 37, 'exactly half: no');
        let spell = Hit { class: HitClass::Spell, ..guarded };
        assert(damage(spell, goblin()) == 42, 'spell reads them');
        let bomb = Hit { class: HitClass::Item, ..guarded };
        assert(damage(bomb, goblin()) == 33, 'bomb does not');
        let trap = Hit { class: HitClass::Trap, ..guarded };
        assert(damage(trap, goblin()) == 33, 'trap does not');
    }

    // §6: a sum below −100 is −100; the hit lands with 0 damage, and is a hit (FX-10).
    #[test]
    #[available_gas(l2_gas: 14889)] // ceil(1.05 × 14180 measured)
    fn test_percent_floor_and_zero_hit() {
        let hit = Hit { percent: -120, weakened: true, ..sword() };
        assert(hit.percent(@goblin(), false) == -100, 'floored');
        let result = landed(hit.resolve(@goblin()));
        assert(result.damage == 0, '0 damage');
        let at = Hit { percent: -100, ..sword() };
        assert(landed(at.resolve(@goblin())).damage == 0, 'at -100');
        let tiny = Hit { base: 0, ..sword() };
        assert(
            tiny
                .resolve(
                    @goblin(),
                ) == HitOutcome::Landed(Landed { damage: 0, critical: false, halved: false }),
            'base 0 lands',
        );
    }

    // §6: damage at both bounds.
    #[test]
    #[available_gas(l2_gas: 38199)] // ceil(1.05 × 36380 measured)
    fn test_damage_bounds() {
        let zero = HitTarget { armor: 0, ..goblin() };
        let top = Hit {
            base: MAX_BASE,
            strength: 255,
            percent: 127,
            percent_above_half: 127,
            health: 1,
            max_health: 1,
            arc: Arc::Back,
            weapon: weapon::AXE,
            ..sword(),
        };
        // x = 255 clamps to 80: 33,022 × 4 = 132,088, × (100 + 319) %: above 65,535, clamped.
        assert(damage(top, zero) == 0xFFFF, 'clamped to 65535');
        // 132,088 × 40 % = 52,835 (52,835.2): under the clamp, truncated.
        assert(top.damage(0, -60) == 52835, 'below the clamp');
        let exact = Hit { base: 16383, strength: 80, ..sword() };
        assert(damage(exact, zero) == 65532, 'just below');
        let low = Hit { base: 1, strength: 0, ..sword() };
        let heavy = HitTarget { armor: 1000, ..goblin() };
        assert(damage(low, heavy) == 0, 'truncated to 0');
    }

    // ---- FX-19: the halving ---------------------------------------------------------------------

    #[test]
    #[available_gas(l2_gas: 84599)] // ceil(1.05 × 80570 measured)
    fn test_halve_first_heavy_hit() {
        let held = HitTarget { halve: true, health: 300, max_health: 480, ..goblin() };
        // 2 × 300 ≥ 480 and 2 × (300 − 100) < 480: halved to 50.
        let hit = Hit { base: 100, ..sword() };
        let result = landed(hit.resolve(@held));
        assert(result.damage == 50 && result.halved, 'halved');
        // 300 − 50 = 250, 500 ≥ 480: not crossing.
        let light = Hit { base: 50, ..sword() };
        assert(!landed(light.resolve(@held)).halved, 'not crossing');
        let below = HitTarget { health: 239, ..held };
        assert(!landed(hit.resolve(@below)).halved, 'already below');
        // Exactly 50 % before: 2h ≥ max holds.
        let half = HitTarget { health: 240, ..held };
        assert(landed(hit.resolve(@half)).damage == 50, 'from exactly half');
        // A killing blow above health: h ⊖ d = 0; halved, truncated: 301 → 150.
        let lethal = Hit { base: 301, ..sword() };
        assert(landed(lethal.resolve(@held)).damage == 150, 'lethal halved');
        let spent = HitTarget { halve: false, ..held };
        assert(landed(hit.resolve(@spent)).damage == 100, 'spent');
        let spell = Hit { class: HitClass::Spell, ..hit };
        assert(!landed(spell.resolve(@held)).halved, 'weapon only');
        assert(held.halve(1) == (1, false), 'a scratch');
    }

    // ---- The worked examples ----------------------------------------------------------------

    // A smoke test from §10.7's numbers: a spell's `DAMAGE` 50 at strength equal to armor deals
    // 50.
    // §10.7's point, a carrier's guard read once for every actor (FX-40), is the executor's and is
    // tested by CBT-05.
    #[test]
    #[available_gas(l2_gas: 15005)] // ceil(1.05 × 14290 measured)
    fn test_spell_at_equal_strength_and_armor() {
        let area = Hit { class: HitClass::Spell, base: 50, strength: 60, ..sword() };
        let target = HitTarget { armor: 60, ..goblin() };
        assert(damage(area, target) == 50, '50');
    }

    // §10.8: a killing blow lands with its full damage; death is the executor's (steps 5–9).
    #[test]
    #[available_gas(l2_gas: 15005)] // ceil(1.05 × 14290 measured)
    fn test_example_10_8() {
        let weak = HitTarget { health: 20, ..goblin() };
        assert(damage(sword(), weak) == 100, 'lands above health');
    }

    // ---- What an input may not be -------------------------------------------------------------

    #[test]
    #[available_gas(l2_gas: 8201)] // ceil(1.05 × 7810 measured)
    #[should_panic(expected: 'hit: base above its bound')]
    fn test_base_refused() {
        HitAssert::assert_valid(@Hit { base: MAX_BASE + 1, ..sword() }, @goblin());
    }

    #[test]
    #[available_gas(l2_gas: 8201)] // ceil(1.05 × 7810 measured)
    #[should_panic(expected: 'hit: health above max')]
    fn test_target_health_refused() {
        HitAssert::assert_valid(@sword(), @HitTarget { health: 101, ..goblin() });
    }

    #[test]
    #[available_gas(l2_gas: 8201)] // ceil(1.05 × 7810 measured)
    #[should_panic(expected: 'hit: health above max')]
    fn test_source_health_refused() {
        HitAssert::assert_valid(@Hit { health: 2, max_health: 1, ..sword() }, @goblin());
    }

    #[test]
    #[available_gas(l2_gas: 8201)] // ceil(1.05 × 7810 measured)
    #[should_panic(expected: 'hit: block charges')]
    fn test_block_refused() {
        HitAssert::assert_valid(@sword(), @HitTarget { block: 64, ..goblin() });
    }

    // ---- No panic on a legal input (D-140) ----------------------------------------------------

    /// The next draw below `bound` of a 64-bit linear congruential sequence (Knuth's MMIX
    /// constants): deterministic, for the tests only.
    fn draw(ref state: u128, bound: u128) -> u128 {
        state = (state * 6364136223846793005 + 1442695040888963407) % 0x10000000000000000;
        (state / 0x100000000) % bound
    }

    fn signed(ref state: u128, low: i32, span: u128) -> i32 {
        let v: i32 = draw(ref state, span).try_into().unwrap();
        low + v
    }

    fn flag(ref state: u128, one_in: u128) -> bool {
        draw(ref state, one_in) == 0
    }

    /// A legal case from a seed: every field over its legal range, the edges often.
    fn case(seed: u64) -> (Hit, HitTarget) {
        let mut s: u128 = seed.into();
        let class = match draw(ref s, 4) {
            0 => HitClass::Weapon,
            1 => HitClass::Spell,
            2 => HitClass::Item,
            _ => HitClass::Trap,
        };
        let arc = match draw(ref s, 4) {
            0 => Arc::Front,
            1 => Arc::FrontSide,
            2 => Arc::RearSide,
            _ => Arc::Back,
        };
        let base = if flag(ref s, 2) {
            draw(ref s, 120)
        } else {
            draw(ref s, MAX_BASE.into() + 1)
        };
        let source_max = draw(ref s, 1000);
        let hit = Hit {
            class,
            weapon: draw(ref s, weapon::LAST.into() + 1).try_into().unwrap(),
            melee: flag(ref s, 2),
            arc,
            in_front: flag(ref s, 2),
            strength: draw(ref s, 766).try_into().unwrap(),
            base: base.try_into().unwrap(),
            percent: signed(ref s, -127, 255).try_into().unwrap(),
            percent_above_half: signed(ref s, -127, 255).try_into().unwrap(),
            penetration: draw(ref s, 301).try_into().unwrap(),
            health: draw(ref s, source_max + 1).try_into().unwrap(),
            max_health: source_max.try_into().unwrap(),
            weakened: flag(ref s, 4),
            blind: flag(ref s, 4),
        };
        let armor = if flag(ref s, 8) {
            signed(ref s, -32768, 65536)
        } else {
            signed(ref s, -300, 1301)
        };
        let block = if flag(ref s, 3) {
            draw(ref s, MAX_BLOCK_U128 + 1)
        } else {
            0
        };
        let max_health = draw(ref s, 2000);
        let target = HitTarget {
            armor: armor.try_into().unwrap(),
            armor_effects: draw(ref s, 1021).try_into().unwrap(),
            armor_stance: signed(ref s, -18, 37).try_into().unwrap(),
            armor_enchanted: signed(ref s, -18, 37).try_into().unwrap(),
            in_stance: flag(ref s, 2),
            enchanted: flag(ref s, 2),
            armor_vs: draw(ref s, 64).try_into().unwrap(),
            block: block.try_into().unwrap(),
            evade: flag(ref s, 3),
            knocked_down: flag(ref s, 4),
            asleep: flag(ref s, 6),
            halve: flag(ref s, 3),
            health: draw(ref s, max_health + 1).try_into().unwrap(),
            max_health: max_health.try_into().unwrap(),
        };
        (hit, target)
    }

    const MAX_BLOCK_U128: u128 = 63;

    // D-140: no legal input panics; the outcome keeps §5.4's invariants.
    #[test]
    #[fuzzer(runs: 256)]
    // gas: raised, CBT-05a: D-179's case and track CV's three hit cases
    #[available_gas(l2_gas: 533211)] // ceil(1.05 × 507820 measured)
    fn test_fuzz_no_panic(seed: u64) {
        let (hit, target) = case(seed);
        match hit.resolve(@target) {
            HitOutcome::Landed(landed) => {
                if hit.class != HitClass::Weapon {
                    assert(!landed.critical && !landed.halved, 'weapon only');
                }
                if landed.critical {
                    assert(
                        hit.arc == Arc::Back || target.knocked_down || target.asleep, 'critical',
                    );
                }
            },
            _ => assert(hit.class == HitClass::Weapon, 'only a weapon hit stops'),
        }
    }

    /// Track CV's hand-picked cases (CBT-05a): (200) an axe from the front-side arc, landing below
    /// the clamp: no axe bonus; (201) the `ABOVE_HALF` damage passive at exactly half health,
    /// with a non-zero percent: it does not apply; (202) FX-19's halving when the hit leaves the
    /// target at exactly half: `2 (h ⊖ d) < max` fails, no halving.
    fn cv_cases() -> Array<(Hit, HitTarget)> {
        array![
            (Hit { weapon: weapon::AXE, arc: Arc::FrontSide, ..sword() }, goblin()),
            (Hit { percent_above_half: 20, health: 50, max_health: 100, ..sword() }, goblin()),
            (
                Hit { base: 60, ..sword() },
                HitTarget { halve: true, health: 300, max_health: 480, ..goblin() },
            ),
        ]
    }

    // Track CV's cases, each pinned: the axe front-side 100 (no +25); above half at exactly half
    // 100 (no +20); 300 − 60 = 240 = half of 480: not halved.
    #[test]
    #[available_gas(l2_gas: 162614)] // ceil(1.05 × 154870 measured)
    fn test_cv_cases() {
        let cases = cv_cases();
        let (axe, target) = *cases[0];
        assert(damage(axe, target) == 100, 'axe front-side: no bonus');
        let (half, target) = *cases[1];
        assert(damage(half, target) == 100, 'exactly half: no above-half');
        let (hit, target) = *cases[2];
        let landed = landed(hit.resolve(@target));
        assert(landed.damage == 60 && !landed.halved, 'left at half: not halved');
    }

    // ---- The vector table for the TypeScript mirror (D-140, SPK-4) ---------------------------

    /// The hand-written cases: the edges above, so that the mirror meets each.
    fn edges() -> Array<(Hit, HitTarget)> {
        let zero = HitTarget { armor: 0, ..goblin() };
        array![
            (sword(), goblin()), (Hit { arc: Arc::Back, ..sword() }, goblin()),
            (Hit { arc: Arc::RearSide, weapon: weapon::AXE, ..sword() }, goblin()),
            (Hit { arc: Arc::Back, weapon: weapon::AXE, ..sword() }, goblin()),
            (sword(), HitTarget { knocked_down: true, block: 2, evade: true, ..goblin() }),
            (sword(), HitTarget { asleep: true, block: 2, ..goblin() }),
            (sword(), HitTarget { asleep: true, evade: true, ..goblin() }),
            (sword(), HitTarget { block: 2, ..goblin() }),
            (Hit { arc: Arc::RearSide, ..sword() }, HitTarget { block: 2, ..goblin() }),
            (Hit { arc: Arc::Back, ..sword() }, HitTarget { evade: true, ..goblin() }),
            (Hit { melee: false, ..sword() }, HitTarget { evade: true, ..goblin() }),
            (Hit { blind: true, in_front: false, ..sword() }, HitTarget { block: 1, ..goblin() }),
            (Hit { blind: true, in_front: true, ..sword() }, goblin()),
            (Hit { weakened: true, arc: Arc::Back, ..sword() }, goblin()),
            (Hit { penetration: 300, ..sword() }, HitTarget { armor: 41, ..goblin() }),
            (Hit { penetration: 25, ..sword() }, HitTarget { armor: -500, ..goblin() }),
            (sword(), HitTarget { armor: -30, armor_effects: 20, armor_vs: 50, ..goblin() }),
            (Hit { strength: 765, ..sword() }, zero),
            (Hit { strength: 0, ..sword() }, HitTarget { armor: 32767, ..goblin() }),
            (Hit { percent: -120, weakened: true, ..sword() }, goblin()),
            (Hit { base: 0, ..sword() }, goblin()),
            (
                Hit {
                    base: MAX_BASE,
                    strength: 255,
                    percent: 127,
                    percent_above_half: 127,
                    health: 1,
                    max_health: 1,
                    arc: Arc::Back,
                    weapon: weapon::AXE,
                    ..sword(),
                },
                zero,
            ),
            (
                Hit { base: 100, ..sword() },
                HitTarget { halve: true, health: 300, max_health: 480, ..goblin() },
            ),
            (
                Hit { base: 301, ..sword() },
                HitTarget { halve: true, health: 300, max_health: 480, ..goblin() },
            ),
            (
                Hit { class: HitClass::Spell, penetration: 100, percent: 15, ..sword() },
                HitTarget { armor: 41, block: 3, knocked_down: true, ..goblin() },
            ),
            (
                Hit { class: HitClass::Item, strength: 200, base: 50, penetration: 100, ..sword() },
                goblin(),
            ),
            (Hit { class: HitClass::Trap, strength: 60, percent: 50, ..sword() }, goblin()),
        ]
    }

    fn hex(felts: Span<felt252>) -> ByteArray {
        let mut out: ByteArray = "[";
        let mut first = true;
        for felt in felts {
            if !first {
                out.append(@",");
            }
            first = false;
            let wide: u256 = (*felt).into();
            out.append(@format!("\"0x{:x}\"", wide));
        }
        out.append(@"]");
        out
    }

    /// Cases in the table: the edges, then legal cases from seeds 1, 2, …
    const VECTORS: u32 = 200;

    // AC-3: the vector table, printed one JSON line per case (`{"id", "case", "ok"}`, SPK-4's
    // form), and a digest of every case and outcome: a change to a rule or to the cases fails here
    // until `contracts/logic/vectors/hit.jsonl` is regenerated (module documentation). FND-23: in
    // five parts of consecutive ids, each with its digest, so that a test's trace stays small.
    fn check_vectors(first: u32, last: u32, expected: felt252) {
        let mut cases = edges();
        let mut seed: u64 = 1;
        while cases.len() < VECTORS {
            cases.append(case(seed));
            seed += 1;
        }
        // Track CV's three (their mutation check of the mirror), after the seeded cases so that
        // no earlier id moves: ids 200, 201, 202.
        cases.append_span(cv_cases().span());
        assert(cases.len() == TOTAL, 'vectors: case count moved');
        let mut digest: Array<felt252> = array![];
        let mut id: u32 = first;
        for (hit, target) in cases.span().slice(first, last - first) {
            let mut input: Array<felt252> = array![];
            hit.serialize(ref input);
            target.serialize(ref input);
            let mut output: Array<felt252> = array![];
            hit.resolve(target).serialize(ref output);
            println!(
                "{{\"id\":{},\"case\":{},\"ok\":{}}}", id, hex(input.span()), hex(output.span()),
            );
            digest.append(core::poseidon::poseidon_hash_span(input.span()));
            digest.append(core::poseidon::poseidon_hash_span(output.span()));
            id += 1;
        }
        let digest = core::poseidon::poseidon_hash_span(digest.span());
        println!("digest {}", digest);
        assert(digest == expected, 'vectors moved: regenerate');
    }

    #[test]
    #[available_gas(l2_gas: 196721826)] // ceil(1.05 × 187354120 measured)
    fn test_vectors_0() {
        check_vectors(0, 41, DIGEST_0);
    }

    #[test]
    #[available_gas(l2_gas: 250046790)] // ceil(1.05 × 238139800 measured)
    fn test_vectors_1() {
        check_vectors(41, 82, DIGEST_1);
    }

    #[test]
    #[available_gas(l2_gas: 263136275)] // ceil(1.05 × 250605976 measured)
    fn test_vectors_2() {
        check_vectors(82, 123, DIGEST_2);
    }

    #[test]
    #[available_gas(l2_gas: 244421575)] // ceil(1.05 × 232782452 measured)
    fn test_vectors_3() {
        check_vectors(123, 164, DIGEST_3);
    }

    #[test]
    #[available_gas(l2_gas: 248287639)] // ceil(1.05 × 236464418 measured)
    fn test_vectors_4() {
        check_vectors(164, TOTAL, DIGEST_4);
    }

    /// The cases of the table: `VECTORS`, then track CV's three.
    const TOTAL: u32 = 203;

    const DIGEST_0: felt252 =
        586421753970926501500974638465701345356105553413818986702921276783755203995;
    const DIGEST_1: felt252 =
        924219708081217976842002592206376387684010835646827443922158919412584381713;
    const DIGEST_2: felt252 =
        3472834525710173403964733565786141887649755441804071880667868155571221440760;
    const DIGEST_3: felt252 =
        1451526976089260957098234498248813736896198721646202816405381569518106911248;
    const DIGEST_4: felt252 =
        3259544917690136778980312074053006567758719917850998568235381858988265320536;
}
